"""Seed script for FoodMatch MVP database."""
import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from datetime import date, timedelta
from app import create_app, db
from app.models.solicitation import Solicitation
from app.models.organization import Organization
from app.models.zip_need_score import ZipNeedScore
from app.models.match_result import MatchResult
from app.models.emergency_capacity import EmergencyCapacity
from app.models.waste_reduction import WasteReduction


def seed():
    app = create_app()
    with app.app_context():
        db.create_all()

        print("Clearing existing data...")
        try:
            WasteReduction.query.delete()
            EmergencyCapacity.query.delete()
            MatchResult.query.delete()
            Solicitation.query.delete()
            Organization.query.delete()
            ZipNeedScore.query.delete()
            db.session.commit()
        except Exception as e:
            db.session.rollback()
            print(f"Clear failed (fresh DB): {e}")

        print("Seeding ZIP need scores...")
        seed_zip_scores()
        db.session.commit()

        print("Seeding solicitations...")
        seed_solicitations()
        db.session.commit()

        print("Seeding organizations...")
        seed_organizations()
        db.session.commit()

        print("Seeding emergency capacities...")
        seed_emergency_capacities()
        db.session.commit()

        print("Seeding waste reduction records...")
        seed_waste_reductions()
        db.session.commit()

        print("Done! Seeded successfully.")


def seed_zip_scores():
    zips = [
        ("38601", 34.3668, -89.5195, "MS", "Abbeville", 0.28, 12000, 0.22, 82),
        ("38614", 33.7490, -90.7351, "MS", "Clarksdale", 0.31, 15000, 0.28, 89),
        ("38701", 33.4015, -91.0618, "MS", "Greenville", 0.29, 32000, 0.25, 85),
        ("72301", 35.2145, -90.1848, "AR", "West Memphis", 0.25, 25000, 0.21, 78),
        ("72401", 35.8423, -90.7043, "AR", "Jonesboro", 0.18, 75000, 0.14, 62),
        ("36601", 30.6944, -88.0431, "AL", "Mobile", 0.22, 190000, 0.19, 74),
        ("36104", 32.3668, -86.2999, "AL", "Montgomery", 0.21, 200000, 0.18, 72),
        ("30303", 33.7490, -84.3880, "GA", "Atlanta", 0.17, 500000, 0.13, 58),
        ("30901", 33.4735, -81.9748, "GA", "Augusta", 0.23, 200000, 0.20, 75),
        ("29401", 32.7765, -79.9311, "SC", "Charleston", 0.14, 140000, 0.10, 48),
        ("29201", 34.0007, -81.0348, "SC", "Columbia", 0.19, 135000, 0.15, 64),
        ("37203", 36.1627, -86.7816, "TN", "Nashville", 0.15, 690000, 0.11, 52),
        ("38103", 35.1495, -90.0490, "TN", "Memphis", 0.26, 650000, 0.23, 80),
        ("70112", 29.9511, -90.0715, "LA", "New Orleans", 0.24, 390000, 0.21, 77),
        ("70801", 30.4515, -91.1871, "LA", "Baton Rouge", 0.20, 225000, 0.17, 68),
        ("39201", 32.2988, -90.1848, "MS", "Jackson", 0.27, 170000, 0.24, 83),
        ("75201", 32.7872, -96.7985, "TX", "Dallas", 0.16, 1300000, 0.12, 55),
        ("77001", 29.7604, -95.3698, "TX", "Houston", 0.18, 2300000, 0.14, 60),
        ("85001", 33.4484, -112.0740, "AZ", "Phoenix", 0.17, 1700000, 0.13, 58),
        ("90011", 33.9425, -118.2551, "CA", "Los Angeles", 0.20, 55000, 0.17, 69),
        ("10451", 40.8207, -73.9234, "NY", "Bronx", 0.23, 45000, 0.20, 76),
        ("60621", 41.7795, -87.6424, "IL", "Chicago", 0.25, 35000, 0.22, 79),
        ("48201", 42.3486, -83.0567, "MI", "Detroit", 0.27, 40000, 0.24, 83),
        ("44101", 41.4993, -81.6944, "OH", "Cleveland", 0.24, 38000, 0.21, 77),
        ("21201", 39.2904, -76.6122, "MD", "Baltimore", 0.22, 42000, 0.19, 73),
        ("19101", 39.9526, -75.1652, "PA", "Philadelphia", 0.21, 55000, 0.18, 71),
        ("02101", 42.3601, -71.0589, "MA", "Boston", 0.13, 65000, 0.09, 45),
        ("33101", 25.7617, -80.1918, "FL", "Miami", 0.19, 470000, 0.15, 65),
        ("32099", 30.3322, -81.6557, "FL", "Jacksonville", 0.18, 950000, 0.14, 62),
        ("28201", 35.2271, -80.8431, "NC", "Charlotte", 0.16, 880000, 0.12, 55),
        ("27601", 35.7796, -78.6382, "NC", "Raleigh", 0.13, 475000, 0.09, 46),
        ("23219", 37.5407, -77.4360, "VA", "Richmond", 0.18, 230000, 0.14, 61),
        ("20001", 38.9072, -77.0369, "DC", "Washington", 0.15, 700000, 0.11, 52),
        ("63101", 38.6270, -90.1994, "MO", "St. Louis", 0.25, 300000, 0.22, 79),
        ("64101", 39.0997, -94.5786, "MO", "Kansas City", 0.19, 500000, 0.15, 64),
        ("55401", 44.9778, -93.2650, "MN", "Minneapolis", 0.14, 430000, 0.10, 48),
        ("53201", 43.0389, -87.9065, "WI", "Milwaukee", 0.22, 590000, 0.19, 73),
        ("46201", 39.7684, -86.1581, "IN", "Indianapolis", 0.19, 880000, 0.15, 64),
        ("40201", 38.2527, -85.7585, "KY", "Louisville", 0.20, 630000, 0.16, 67),
        ("73101", 35.4676, -97.5164, "OK", "Oklahoma City", 0.19, 680000, 0.15, 64),
        ("71101", 32.5252, -93.7502, "LA", "Shreveport", 0.24, 190000, 0.21, 77),
        ("79901", 31.7619, -106.4850, "TX", "El Paso", 0.22, 680000, 0.19, 73),
        ("87101", 35.0844, -106.6504, "NM", "Albuquerque", 0.20, 560000, 0.16, 67),
        ("29301", 34.9496, -81.9321, "SC", "Spartanburg", 0.21, 38000, 0.18, 70),
        ("31201", 32.8407, -83.6324, "GA", "Macon", 0.24, 153000, 0.21, 77),
        ("35801", 34.7304, -86.5861, "AL", "Huntsville", 0.15, 215000, 0.11, 51),
        ("37601", 36.3134, -82.3535, "TN", "Johnson City", 0.17, 67000, 0.13, 57),
        ("42101", 36.9903, -86.4436, "KY", "Bowling Green", 0.18, 75000, 0.14, 61),
        ("50301", 41.5868, -93.6250, "IA", "Des Moines", 0.15, 215000, 0.11, 52),
        ("68101", 41.2565, -95.9345, "NE", "Omaha", 0.16, 490000, 0.12, 55),
    ]
    for z in zips:
        db.session.add(ZipNeedScore(
            zip_code=z[0], lat=z[1], lng=z[2], state=z[3], city=z[4],
            food_insecurity_rate=z[5], population=z[6],
            snap_participation_rate=z[7], need_score=z[8],
        ))


def seed_solicitations():
    today = date.today()
    sols = [
        {
            "title": "USDA Fresh Produce Distribution - Mississippi Delta",
            "description": "Seeking suppliers for fresh fruit and vegetable distribution to food-insecure communities in the Mississippi Delta region. Must have cold chain capability and last-mile delivery experience.",
            "agency": "USDA Food and Nutrition Service",
            "naics_code": "311991",
            "set_aside_type": "Small Business",
            "zip_code": "38614",
            "lat": 33.7490, "lng": -90.7351,
            "categories": ["fresh produce", "cold storage", "last mile delivery"],
            "estimated_value": 450000, "status": "open",
            "posted_date": today - timedelta(days=5),
            "response_deadline": today + timedelta(days=25),
        },
        {
            "title": "School District Meal Program - Memphis Metro",
            "description": "Supply and deliver nutritious meals to 45 schools across the Memphis metropolitan area. Requires USDA compliance and experience with institutional food service.",
            "agency": "Memphis-Shelby County Schools",
            "naics_code": "722310",
            "set_aside_type": None,
            "zip_code": "38103",
            "lat": 35.1495, "lng": -90.0490,
            "categories": ["meal preparation", "institutional food service", "last mile delivery"],
            "estimated_value": 1200000, "status": "open",
            "posted_date": today - timedelta(days=10),
            "response_deadline": today + timedelta(days=20),
        },
        {
            "title": "Emergency Food Bank Supply Chain - New Orleans",
            "description": "Establish emergency food supply chain for disaster preparedness in New Orleans area food banks. Includes shelf-stable goods, cold storage, and distribution logistics.",
            "agency": "Louisiana Department of Agriculture",
            "naics_code": "493110",
            "set_aside_type": "8(a)",
            "zip_code": "70112",
            "lat": 29.9511, "lng": -90.0715,
            "categories": ["shelf-stable goods", "cold storage", "warehouse distribution", "emergency supply"],
            "estimated_value": 750000, "status": "open",
            "posted_date": today - timedelta(days=3),
            "response_deadline": today + timedelta(days=30),
        },
        {
            "title": "SNAP Distribution Technology Platform",
            "description": "Develop and manage electronic SNAP benefit distribution platform for rural Alabama communities. Must integrate with existing POS systems.",
            "agency": "Alabama Department of Human Resources",
            "naics_code": "541511",
            "set_aside_type": "HUBZone",
            "zip_code": "36601",
            "lat": 30.6944, "lng": -88.0431,
            "categories": ["SNAP distribution", "technology platform", "rural outreach"],
            "estimated_value": 320000, "status": "open",
            "posted_date": today - timedelta(days=7),
            "response_deadline": today + timedelta(days=35),
        },
        {
            "title": "Cold Chain Infrastructure - Atlanta Food Hub",
            "description": "Build and operate cold chain infrastructure for the Atlanta Regional Food Hub connecting local farms to food-insecure urban neighborhoods.",
            "agency": "Georgia Department of Agriculture",
            "naics_code": "493120",
            "set_aside_type": "Small Business",
            "zip_code": "30303",
            "lat": 33.7490, "lng": -84.3880,
            "categories": ["cold storage", "food hub operations", "local sourcing", "warehouse distribution"],
            "estimated_value": 890000, "status": "open",
            "posted_date": today - timedelta(days=2),
            "response_deadline": today + timedelta(days=28),
        },
        {
            "title": "Mobile Food Pantry Fleet - Rural Arkansas",
            "description": "Operate mobile food pantry vehicles serving rural communities in eastern Arkansas with limited grocery access. Weekly routes to 12 communities.",
            "agency": "Arkansas Department of Human Services",
            "naics_code": "624210",
            "set_aside_type": None,
            "zip_code": "72301",
            "lat": 35.2145, "lng": -90.1848,
            "categories": ["mobile food pantry", "last mile delivery", "rural outreach", "fresh produce"],
            "estimated_value": 280000, "status": "open",
            "posted_date": today - timedelta(days=8),
            "response_deadline": today + timedelta(days=22),
        },
        {
            "title": "USDA Commodity Distribution - South Carolina",
            "description": "Distribute USDA commodity foods to eligible households across 15 counties in South Carolina. Requires warehouse space and refrigerated transport.",
            "agency": "USDA Food Distribution Program",
            "naics_code": "493110",
            "set_aside_type": "Small Business",
            "zip_code": "29201",
            "lat": 34.0007, "lng": -81.0348,
            "categories": ["warehouse distribution", "refrigerated transport", "USDA commodities"],
            "estimated_value": 520000, "status": "open",
            "posted_date": today - timedelta(days=12),
            "response_deadline": today + timedelta(days=18),
        },
        {
            "title": "Farm to School Program - Nashville",
            "description": "Coordinate farm-to-school supply chain connecting Tennessee farms with Nashville area school cafeterias. Focus on fresh, locally-grown produce.",
            "agency": "Tennessee Department of Agriculture",
            "naics_code": "424480",
            "set_aside_type": None,
            "zip_code": "37203",
            "lat": 36.1627, "lng": -86.7816,
            "categories": ["local sourcing", "fresh produce", "institutional food service", "farm to school"],
            "estimated_value": 350000, "status": "open",
            "posted_date": today - timedelta(days=6),
            "response_deadline": today + timedelta(days=24),
        },
        {
            "title": "Food Desert Intervention - South Side Chicago",
            "description": "Multi-year program to establish food access points in Chicago South Side food deserts. Includes mobile markets, community gardens support, and retail partnerships.",
            "agency": "City of Chicago Department of Family and Support Services",
            "naics_code": "624210",
            "set_aside_type": "8(a)",
            "zip_code": "60621",
            "lat": 41.7795, "lng": -87.6424,
            "categories": ["mobile food pantry", "community nutrition", "retail partnerships", "fresh produce"],
            "estimated_value": 1500000, "status": "open",
            "posted_date": today - timedelta(days=1),
            "response_deadline": today + timedelta(days=40),
        },
        {
            "title": "Tribal Food Sovereignty Program - New Mexico",
            "description": "Support indigenous food sovereignty initiatives across Pueblo communities in New Mexico. Includes traditional food preservation, distribution, and cultural food programming.",
            "agency": "USDA Office of Tribal Relations",
            "naics_code": "624210",
            "set_aside_type": "Indian Economic Enterprise",
            "zip_code": "87101",
            "lat": 35.0844, "lng": -106.6504,
            "categories": ["community nutrition", "food preservation", "cultural food programs", "rural outreach"],
            "estimated_value": 420000, "status": "open",
            "posted_date": today - timedelta(days=4),
            "response_deadline": today + timedelta(days=32),
        },
        {
            "title": "Senior Meal Delivery Program - Detroit",
            "description": "Home-delivered meal program for homebound seniors in Detroit metropolitan area. 5 days/week, hot and cold meal options, dietary accommodation required.",
            "agency": "Michigan Department of Health and Human Services",
            "naics_code": "624120",
            "set_aside_type": None,
            "zip_code": "48201",
            "lat": 42.3486, "lng": -83.0567,
            "categories": ["meal preparation", "last mile delivery", "senior nutrition", "dietary accommodation"],
            "estimated_value": 680000, "status": "open",
            "posted_date": today - timedelta(days=9),
            "response_deadline": today + timedelta(days=21),
        },
        {
            "title": "Refrigerated Warehouse Expansion - Jackson MS",
            "description": "Expand refrigerated warehouse capacity for Mississippi state food distribution center. 25,000 sq ft addition with modern cold chain management.",
            "agency": "Mississippi Department of Agriculture",
            "naics_code": "493120",
            "set_aside_type": "HUBZone",
            "zip_code": "39201",
            "lat": 32.2988, "lng": -90.1848,
            "categories": ["cold storage", "warehouse distribution", "infrastructure"],
            "estimated_value": 2100000, "status": "open",
            "posted_date": today - timedelta(days=15),
            "response_deadline": today + timedelta(days=45),
        },
        {
            "title": "WIC Farmer's Market Program - Philadelphia",
            "description": "Administer WIC Farmers Market Nutrition Program across 20 market locations in Philadelphia.",
            "agency": "Pennsylvania Department of Health",
            "naics_code": "624190",
            "set_aside_type": "Small Business",
            "zip_code": "19101",
            "lat": 39.9526, "lng": -75.1652,
            "categories": ["farmers market", "SNAP distribution", "community nutrition", "local sourcing"],
            "estimated_value": 190000, "status": "open",
            "posted_date": today - timedelta(days=11),
            "response_deadline": today + timedelta(days=19),
        },
        {
            "title": "Disaster Food Relief Staging - Houston",
            "description": "Establish permanent disaster food relief staging area in Houston. Hurricane season readiness with shelf-stable food stockpiles and rapid distribution capability.",
            "agency": "FEMA Region 6",
            "naics_code": "493110",
            "set_aside_type": None,
            "zip_code": "77001",
            "lat": 29.7604, "lng": -95.3698,
            "categories": ["emergency supply", "shelf-stable goods", "warehouse distribution", "disaster relief"],
            "estimated_value": 950000, "status": "open",
            "posted_date": today - timedelta(days=14),
            "response_deadline": today + timedelta(days=36),
        },
        {
            "title": "Community Kitchen Incubator - Baltimore",
            "description": "Launch shared commercial kitchen incubator for food entrepreneurs in East Baltimore.",
            "agency": "Baltimore Development Corporation",
            "naics_code": "722514",
            "set_aside_type": "8(a)",
            "zip_code": "21201",
            "lat": 39.2904, "lng": -76.6122,
            "categories": ["community nutrition", "food hub operations", "culinary training"],
            "estimated_value": 600000, "status": "open",
            "posted_date": today - timedelta(days=13),
            "response_deadline": today + timedelta(days=27),
        },
        {
            "title": "Produce Gleaning and Rescue - Central Valley CA",
            "description": "Coordinate produce gleaning program with Central Valley farms.",
            "agency": "California Department of Food and Agriculture",
            "naics_code": "424480",
            "set_aside_type": "Small Business",
            "zip_code": "90011",
            "lat": 33.9425, "lng": -118.2551,
            "categories": ["fresh produce", "food rescue", "local sourcing", "warehouse distribution"],
            "estimated_value": 380000, "status": "open",
            "posted_date": today - timedelta(days=6),
            "response_deadline": today + timedelta(days=26),
        },
        {
            "title": "School Breakfast Expansion - Bronx NY",
            "description": "Expand universal free breakfast program to all Bronx public schools. Requires daily delivery of breakfast items to 120+ school locations.",
            "agency": "NYC Department of Education",
            "naics_code": "722310",
            "set_aside_type": None,
            "zip_code": "10451",
            "lat": 40.8207, "lng": -73.9234,
            "categories": ["meal preparation", "institutional food service", "last mile delivery"],
            "estimated_value": 2800000, "status": "open",
            "posted_date": today - timedelta(days=2),
            "response_deadline": today + timedelta(days=38),
        },
        {
            "title": "Halal/Kosher Food Bank Supply - Dearborn MI",
            "description": "Supply culturally appropriate halal and kosher food items to food banks serving diverse communities.",
            "agency": "Michigan Department of Agriculture",
            "naics_code": "311999",
            "set_aside_type": "Small Business",
            "zip_code": "48201",
            "lat": 42.3486, "lng": -83.0567,
            "categories": ["specialty food supply", "cultural food programs", "warehouse distribution"],
            "estimated_value": 230000, "status": "open",
            "posted_date": today - timedelta(days=7),
            "response_deadline": today + timedelta(days=23),
        },
        {
            "title": "TEFAP Distribution Network - Ohio",
            "description": "Manage The Emergency Food Assistance Program distribution across 20 Ohio counties.",
            "agency": "Ohio Department of Job and Family Services",
            "naics_code": "493110",
            "set_aside_type": None,
            "zip_code": "44101",
            "lat": 41.4993, "lng": -81.6944,
            "categories": ["warehouse distribution", "refrigerated transport", "USDA commodities", "emergency supply"],
            "estimated_value": 870000, "status": "open",
            "posted_date": today - timedelta(days=10),
            "response_deadline": today + timedelta(days=30),
        },
        {
            "title": "Summer Feeding Program - Rural Kentucky",
            "description": "Operate Summer Food Service Program at 35 sites across rural eastern Kentucky.",
            "agency": "Kentucky Department of Education",
            "naics_code": "722310",
            "set_aside_type": "HUBZone",
            "zip_code": "42101",
            "lat": 36.9903, "lng": -86.4436,
            "categories": ["meal preparation", "last mile delivery", "rural outreach", "institutional food service"],
            "estimated_value": 410000, "status": "open",
            "posted_date": today - timedelta(days=4),
            "response_deadline": today + timedelta(days=20),
        },
        {
            "title": "Urban Agriculture Support - Cleveland",
            "description": "Provide technical assistance and supply chain support for urban farms in Cleveland.",
            "agency": "USDA Agricultural Marketing Service",
            "naics_code": "115112",
            "set_aside_type": "Small Business",
            "zip_code": "44101",
            "lat": 41.4993, "lng": -81.6944,
            "categories": ["local sourcing", "food hub operations", "community nutrition", "fresh produce"],
            "estimated_value": 275000, "status": "open",
            "posted_date": today - timedelta(days=8),
            "response_deadline": today + timedelta(days=32),
        },
        {
            "title": "Border Community Food Access - El Paso",
            "description": "Improve food access in El Paso colonias and underserved border communities.",
            "agency": "Texas Health and Human Services Commission",
            "naics_code": "624210",
            "set_aside_type": None,
            "zip_code": "79901",
            "lat": 31.7619, "lng": -106.4850,
            "categories": ["mobile food pantry", "SNAP distribution", "community nutrition", "rural outreach"],
            "estimated_value": 340000, "status": "open",
            "posted_date": today - timedelta(days=5),
            "response_deadline": today + timedelta(days=25),
        },
        {
            "title": "Food Recovery & Composting - Miami-Dade",
            "description": "Establish food recovery program with restaurants and grocers in Miami-Dade County.",
            "agency": "Miami-Dade County Solid Waste Management",
            "naics_code": "562219",
            "set_aside_type": "Small Business",
            "zip_code": "33101",
            "lat": 25.7617, "lng": -80.1918,
            "categories": ["food rescue", "warehouse distribution", "community nutrition"],
            "estimated_value": 520000, "status": "open",
            "posted_date": today - timedelta(days=3),
            "response_deadline": today + timedelta(days=28),
        },
        {
            "title": "Native American Food Distribution - Oklahoma",
            "description": "USDA Food Distribution Program on Indian Reservations (FDPIR) for Oklahoma tribal nations.",
            "agency": "USDA Food and Nutrition Service",
            "naics_code": "624210",
            "set_aside_type": "Indian Economic Enterprise",
            "zip_code": "73101",
            "lat": 35.4676, "lng": -97.5164,
            "categories": ["USDA commodities", "warehouse distribution", "cultural food programs", "rural outreach"],
            "estimated_value": 710000, "status": "open",
            "posted_date": today - timedelta(days=11),
            "response_deadline": today + timedelta(days=34),
        },
        {
            "title": "Medically Tailored Meals - Richmond VA",
            "description": "Provide medically tailored meals to individuals with chronic conditions through Medicaid waiver program.",
            "agency": "Virginia Department of Medical Assistance Services",
            "naics_code": "624120",
            "set_aside_type": None,
            "zip_code": "23219",
            "lat": 37.5407, "lng": -77.4360,
            "categories": ["meal preparation", "dietary accommodation", "last mile delivery", "senior nutrition"],
            "estimated_value": 580000, "status": "open",
            "posted_date": today - timedelta(days=9),
            "response_deadline": today + timedelta(days=31),
        },
        {
            "title": "Regional Food Bank Cold Storage - St. Louis",
            "description": "Install and manage industrial cold storage system for St. Louis Area Foodbank. 40,000 sq ft facility.",
            "agency": "Missouri Department of Social Services",
            "naics_code": "493120",
            "set_aside_type": "Small Business",
            "zip_code": "63101",
            "lat": 38.6270, "lng": -90.1994,
            "categories": ["cold storage", "warehouse distribution", "infrastructure"],
            "estimated_value": 1800000, "status": "open",
            "posted_date": today - timedelta(days=16),
            "response_deadline": today + timedelta(days=44),
        },
        {
            "title": "Nutrition Education & Cooking Classes - DC",
            "description": "Deliver nutrition education and cooking skills program across 25 community sites in Washington DC.",
            "agency": "DC Department of Health",
            "naics_code": "611699",
            "set_aside_type": "8(a)",
            "zip_code": "20001",
            "lat": 38.9072, "lng": -77.0369,
            "categories": ["community nutrition", "culinary training", "rural outreach"],
            "estimated_value": 165000, "status": "open",
            "posted_date": today - timedelta(days=6),
            "response_deadline": today + timedelta(days=22),
        },
        {
            "title": "Grocery Delivery for Homebound - Milwaukee",
            "description": "Grocery delivery service for homebound individuals in Milwaukee County.",
            "agency": "Milwaukee County Department on Aging",
            "naics_code": "492210",
            "set_aside_type": None,
            "zip_code": "53201",
            "lat": 43.0389, "lng": -87.9065,
            "categories": ["last mile delivery", "senior nutrition", "retail partnerships"],
            "estimated_value": 290000, "status": "open",
            "posted_date": today - timedelta(days=7),
            "response_deadline": today + timedelta(days=21),
        },
        {
            "title": "Midwest Produce Hub - Indianapolis",
            "description": "Establish regional produce aggregation hub in Indianapolis connecting farms to institutional buyers.",
            "agency": "Indiana State Department of Agriculture",
            "naics_code": "424480",
            "set_aside_type": "Small Business",
            "zip_code": "46201",
            "lat": 39.7684, "lng": -86.1581,
            "categories": ["food hub operations", "local sourcing", "fresh produce", "warehouse distribution"],
            "estimated_value": 1100000, "status": "open",
            "posted_date": today - timedelta(days=13),
            "response_deadline": today + timedelta(days=37),
        },
        {
            "title": "Emergency SNAP Replacement - Jacksonville FL",
            "description": "Provide emergency SNAP benefit replacement and food distribution following natural disasters.",
            "agency": "Florida Department of Children and Families",
            "naics_code": "624210",
            "set_aside_type": None,
            "zip_code": "32099",
            "lat": 30.3322, "lng": -81.6557,
            "categories": ["SNAP distribution", "emergency supply", "last mile delivery", "disaster relief"],
            "estimated_value": 430000, "status": "open",
            "posted_date": today - timedelta(days=2),
            "response_deadline": today + timedelta(days=26),
        },
    ]
    for s in sols:
        s["source_type"] = "government"
        db.session.add(Solicitation(**s))


def seed_organizations():
    orgs = [
        # ── SUPPLIERS (IDs 1–12) ──────────────────────
        {
            "name": "Delta Fresh Foods Co-op",
            "org_type": "supplier",
            "description": "Farmer-owned cooperative specializing in fresh produce distribution across the Mississippi Delta.",
            "zip_code": "38701", "lat": 33.4015, "lng": -91.0618,
            "contact_email": "contact@deltafreshfoods.coop",
            "capabilities": ["fresh produce", "local sourcing", "cold storage", "last mile delivery"],
            "certifications": ["USDA", "SBA 8(a)", "HUBZone"],
            "service_radius_miles": 500,
            "naics_codes": ["311991", "424480", "493110"], "uei": "DFF4K7M2X1R3",
            "services_description": "Full-service fresh produce aggregation and distribution. Operates cold storage facilities and farm-to-table supply chains across the Mississippi Delta.",
            "past_performance": [
                {"contract": "USDA Fresh Produce Distribution", "agency": "USDA FNS", "value": 380000, "year": 2024, "description": "Distributed 1.2M lbs of fresh produce to 45 food banks."},
                {"contract": "Delta Region Farm-to-School", "agency": "MS Dept of Agriculture", "value": 210000, "year": 2023, "description": "Supplied fresh local produce to 32 school districts."},
            ],
            "annual_revenue": 4200000, "employee_count": 45, "years_in_business": 12, "small_business": True,
        },
        {
            "name": "Bayou Provisions LLC",
            "org_type": "supplier",
            "description": "Louisiana-based food supplier specializing in shelf-stable goods and emergency food supplies.",
            "zip_code": "70112", "lat": 29.9511, "lng": -90.0715,
            "contact_email": "sales@bayouprovisions.com",
            "capabilities": ["shelf-stable goods", "emergency supply", "warehouse distribution", "disaster relief"],
            "certifications": ["SBA 8(a)", "FEMA vendor"],
            "service_radius_miles": 600,
            "naics_codes": ["493110", "311991", "424490"], "uei": "BPL3M7W9X5H2",
            "services_description": "Emergency food supply specialists. Large-scale shelf-stable food staging and rapid deployment for hurricane and disaster preparedness.",
            "past_performance": [
                {"contract": "Hurricane Season Staging", "agency": "FEMA Region 6", "value": 750000, "year": 2024, "description": "Pre-positioned 200,000 MREs and 500,000 water bottles."},
                {"contract": "LA Emergency Food Reserve", "agency": "Louisiana GOHSEP", "value": 420000, "year": 2023, "description": "Maintained state emergency food reserve."},
            ],
            "annual_revenue": 6800000, "employee_count": 55, "years_in_business": 15, "small_business": True,
        },
        {
            "name": "Heartland Meal Services",
            "org_type": "supplier",
            "description": "Institutional meal preparation company serving schools, senior centers, and correctional facilities across the Midwest.",
            "zip_code": "46201", "lat": 39.7684, "lng": -86.1581,
            "contact_email": "contracts@heartlandmeals.com",
            "capabilities": ["meal preparation", "institutional food service", "dietary accommodation", "last mile delivery", "cold storage"],
            "certifications": ["USDA", "ServSafe"],
            "service_radius_miles": 600,
            "naics_codes": ["722310", "624120", "311991"], "uei": "HMS2K6P4R8N3",
            "services_description": "Institutional meal preparation and delivery for schools, senior centers, healthcare facilities. USDA-compliant kitchen facilities.",
            "past_performance": [
                {"contract": "IN School Meal Program", "agency": "Indiana DOE", "value": 1100000, "year": 2024, "description": "Prepared and delivered 2.5M meals to 85 schools."},
                {"contract": "Midwest Senior Meals", "agency": "ACL/AoA", "value": 680000, "year": 2023, "description": "Home-delivered meals to 4,200 homebound seniors."},
            ],
            "annual_revenue": 9200000, "employee_count": 110, "years_in_business": 20, "small_business": False,
        },
        {
            "name": "TechBridge Solutions",
            "org_type": "supplier",
            "description": "Technology company specializing in government food assistance program platforms.",
            "zip_code": "36104", "lat": 32.3668, "lng": -86.2999,
            "contact_email": "gov@techbridgesolutions.com",
            "capabilities": ["technology platform", "SNAP distribution", "rural outreach"],
            "certifications": ["HUBZone", "FedRAMP"],
            "service_radius_miles": 2000,
            "naics_codes": ["541511", "541519", "518210"], "uei": "TBS6H4M8Q2V5",
            "services_description": "Government food assistance technology platforms. SNAP/WIC/TANF benefit management systems and EBT integration.",
            "past_performance": [
                {"contract": "AL SNAP Technology Platform", "agency": "Alabama DHR", "value": 320000, "year": 2024, "description": "Deployed SNAP benefit management system serving 800,000 recipients."},
                {"contract": "Multi-State WIC Integration", "agency": "USDA FNS", "value": 540000, "year": 2023, "description": "WIC EBT integration platform deployed in 3 states."},
            ],
            "annual_revenue": 3800000, "employee_count": 42, "years_in_business": 8, "small_business": True,
        },
        {
            "name": "Lone Star Food Systems",
            "org_type": "supplier",
            "description": "Texas-based food systems company operating cold storage facilities and distribution networks.",
            "zip_code": "75201", "lat": 32.7872, "lng": -96.7985,
            "contact_email": "government@lonestarfood.com",
            "capabilities": ["cold storage", "warehouse distribution", "institutional food service", "shelf-stable goods", "refrigerated transport"],
            "certifications": ["USDA", "DoD vendor", "HUBZone"],
            "service_radius_miles": 800,
            "naics_codes": ["493120", "311991", "722310"], "uei": "LSF7T3W9K5N2",
            "services_description": "Large-scale food systems operation with cold storage and distribution networks. Serves military installations, schools, and government programs.",
            "past_performance": [
                {"contract": "DoD Food Supply - Fort Hood", "agency": "Defense Logistics Agency", "value": 2800000, "year": 2024, "description": "Full food supply chain for military installation."},
                {"contract": "TX School Nutrition Program", "agency": "Texas Dept of Agriculture", "value": 1100000, "year": 2023, "description": "Meal preparation and distribution for 200 school districts."},
            ],
            "annual_revenue": 22000000, "employee_count": 210, "years_in_business": 28, "small_business": False,
        },
        {
            "name": "Midwest Senior Nutrition Inc",
            "org_type": "supplier",
            "description": "Specialized provider of senior nutrition services including Meals on Wheels and medically tailored meals.",
            "zip_code": "53201", "lat": 43.0389, "lng": -87.9065,
            "contact_email": "info@midwestseniornutrition.com",
            "capabilities": ["meal preparation", "senior nutrition", "dietary accommodation", "last mile delivery"],
            "certifications": ["USDA", "ServSafe"],
            "service_radius_miles": 500,
            "naics_codes": ["624120", "722310", "311991"], "uei": "MSN5K3P7R2V4",
            "services_description": "Senior nutrition specialist providing Meals on Wheels, congregate meals, and medically tailored meals.",
            "past_performance": [
                {"contract": "WI Meals on Wheels", "agency": "Milwaukee County DoA", "value": 290000, "year": 2024, "description": "Daily meal delivery to 1,500+ homebound seniors."},
                {"contract": "Midwest MTM Program", "agency": "CMS Medicaid Waiver", "value": 580000, "year": 2023, "description": "Medically tailored meals for 800 chronically ill patients."},
            ],
            "annual_revenue": 4500000, "employee_count": 55, "years_in_business": 14, "small_business": True,
        },
        {
            "name": "Sooner State Food Co-op",
            "org_type": "supplier",
            "description": "Oklahoma cooperative of Native American food producers. Specializes in traditional foods and USDA commodity distribution.",
            "zip_code": "73101", "lat": 35.4676, "lng": -97.5164,
            "contact_email": "coop@soonerfood.org",
            "capabilities": ["USDA commodities", "cultural food programs", "warehouse distribution", "rural outreach"],
            "certifications": ["Indian Economic Enterprise", "USDA", "SBA 8(a)"],
            "service_radius_miles": 600,
            "naics_codes": ["424490", "311999", "624210"], "uei": "SSF8M2N6K4R1",
            "services_description": "Native American food cooperative. USDA commodity distribution for tribal communities and culturally appropriate food programs.",
            "past_performance": [
                {"contract": "OK FDPIR Distribution", "agency": "USDA FNS", "value": 710000, "year": 2024, "description": "Monthly food package distribution to 8,000+ households."},
                {"contract": "Tribal Food Sovereignty", "agency": "USDA NIFA", "value": 220000, "year": 2023, "description": "Traditional food production training for 5 tribal communities."},
            ],
            "annual_revenue": 3600000, "employee_count": 40, "years_in_business": 11, "small_business": True,
        },
        {
            "name": "Pacific Coast Organics",
            "org_type": "supplier",
            "description": "Organic produce supplier serving West Coast food banks and school districts with farm-fresh fruits and vegetables.",
            "zip_code": "90011", "lat": 33.9425, "lng": -118.2551,
            "contact_email": "sales@pacificcoastorganics.com",
            "capabilities": ["fresh produce", "local sourcing", "food rescue", "cold storage", "institutional food service"],
            "certifications": ["USDA", "GAP Certified", "Small Business"],
            "service_radius_miles": 800,
            "naics_codes": ["424480", "311991", "493110"], "uei": "PCO3R8M5K2V7",
            "services_description": "Organic produce aggregation from 150+ farms. Supplies school districts, food banks, and institutional buyers across the West Coast.",
            "past_performance": [
                {"contract": "CA Farm to School", "agency": "CA Dept of Food & Agriculture", "value": 560000, "year": 2024, "description": "Supplied organic produce to 300 schools across Southern California."},
                {"contract": "LA Food Bank Supply", "agency": "LA Regional Food Bank", "value": 340000, "year": 2023, "description": "Weekly delivery of 50,000 lbs fresh produce to 45 distribution sites."},
            ],
            "annual_revenue": 7200000, "employee_count": 68, "years_in_business": 16, "small_business": True,
        },
        {
            "name": "Northeast Emergency Provisions",
            "org_type": "supplier",
            "description": "Emergency food supply company serving the Northeast corridor with MREs, water, and shelf-stable supplies.",
            "zip_code": "10451", "lat": 40.8207, "lng": -73.9234,
            "contact_email": "ops@neeprovisions.com",
            "capabilities": ["emergency supply", "shelf-stable goods", "disaster relief", "warehouse distribution", "last mile delivery"],
            "certifications": ["FEMA vendor", "USDA", "SBA 8(a)"],
            "service_radius_miles": 700,
            "naics_codes": ["493110", "311991", "424490"], "uei": "NEP6W4K8M2R3",
            "services_description": "Northeast emergency food staging and rapid deployment. 80,000 sq ft warehouse with MRE assembly and water bottling lines.",
            "past_performance": [
                {"contract": "NYC Emergency Food Reserve", "agency": "NYC Office of Emergency Mgmt", "value": 890000, "year": 2024, "description": "Maintained 500,000 MREs and 1M water bottles for NYC emergency reserve."},
                {"contract": "NE Winter Storm Response", "agency": "FEMA Region 2", "value": 420000, "year": 2023, "description": "Deployed emergency food to 6 states during winter storm."},
            ],
            "annual_revenue": 8900000, "employee_count": 78, "years_in_business": 18, "small_business": False,
        },
        {
            "name": "Dixie Farms Fresh",
            "org_type": "supplier",
            "description": "Southeast produce aggregator connecting small farms to institutional buyers, food banks, and school districts.",
            "zip_code": "30901", "lat": 33.4735, "lng": -81.9748,
            "contact_email": "orders@dixiefarmsfresh.com",
            "capabilities": ["fresh produce", "local sourcing", "cold storage", "refrigerated transport", "food hub operations"],
            "certifications": ["USDA", "GAP Certified", "Small Business"],
            "service_radius_miles": 500,
            "naics_codes": ["424480", "493110", "484110"], "uei": "DFR5N7K3M9W2",
            "services_description": "Regional produce aggregation hub. Connects 200+ Southeast farms to institutional buyers with cold chain integrity.",
            "past_performance": [
                {"contract": "GA Farm-to-Food Bank", "agency": "GA Dept of Agriculture", "value": 420000, "year": 2024, "description": "Supplied produce from 80 farms to 60 food bank locations."},
                {"contract": "SE School Produce Supply", "agency": "USDA AMS", "value": 650000, "year": 2023, "description": "Fresh produce delivery to 200 schools across GA, SC, NC."},
            ],
            "annual_revenue": 5800000, "employee_count": 52, "years_in_business": 14, "small_business": True,
        },
        {
            "name": "Heartland Grain & Staples",
            "org_type": "supplier",
            "description": "Midwest grain and shelf-stable food supplier providing bulk commodities to food banks and government programs.",
            "zip_code": "50301", "lat": 41.5868, "lng": -93.6250,
            "contact_email": "sales@heartlandgrain.com",
            "capabilities": ["shelf-stable goods", "USDA commodities", "warehouse distribution", "food hub operations"],
            "certifications": ["USDA", "SQF Certified", "Small Business"],
            "service_radius_miles": 800,
            "naics_codes": ["424510", "311211", "493110"], "uei": "HGS4M8K2R6V3",
            "services_description": "Bulk grain, rice, beans, and shelf-stable food production and distribution. 200,000 sq ft facility with grain processing and packaging.",
            "past_performance": [
                {"contract": "TEFAP Commodity Supply", "agency": "USDA FNS", "value": 1200000, "year": 2024, "description": "Supplied 5M lbs of shelf-stable foods to 8-state TEFAP network."},
                {"contract": "Midwest Food Bank Supply", "agency": "Feeding America", "value": 780000, "year": 2023, "description": "Bulk staples supply to 120 food banks across 6 states."},
            ],
            "annual_revenue": 11500000, "employee_count": 95, "years_in_business": 22, "small_business": False,
        },
        {
            "name": "Border Fresh Produce Co",
            "org_type": "supplier",
            "description": "El Paso-based supplier importing fresh produce and providing bilingual food assistance program support.",
            "zip_code": "79901", "lat": 31.7619, "lng": -106.4850,
            "contact_email": "sales@borderfreshproduce.com",
            "capabilities": ["fresh produce", "community nutrition", "mobile food pantry", "SNAP distribution", "cultural food programs"],
            "certifications": ["USDA", "FDA", "Small Business"],
            "service_radius_miles": 500,
            "naics_codes": ["424480", "624210", "311991"], "uei": "BFP2K6N4R8M3",
            "services_description": "Fresh produce supply with bilingual community outreach. Mobile food pantry operations and SNAP enrollment in border communities.",
            "past_performance": [
                {"contract": "TX Border Food Access", "agency": "TX HHSC", "value": 340000, "year": 2024, "description": "Mobile markets serving 15 colonias with 25,000 residents."},
                {"contract": "El Paso School Produce", "agency": "El Paso ISD", "value": 280000, "year": 2023, "description": "Daily fresh produce delivery to 60 schools."},
            ],
            "annual_revenue": 3200000, "employee_count": 38, "years_in_business": 10, "small_business": True,
        },
        # ── DISTRIBUTORS (IDs 13–22) ──────────────────
        {
            "name": "Southern Cold Chain Logistics",
            "org_type": "distributor",
            "description": "Full-service cold chain logistics provider serving the Southeast US. Fleet of 50+ refrigerated trucks.",
            "zip_code": "30303", "lat": 33.7490, "lng": -84.3880,
            "contact_email": "ops@southerncoldchain.com",
            "capabilities": ["cold storage", "refrigerated transport", "warehouse distribution", "last mile delivery"],
            "certifications": ["USDA", "FDA"],
            "service_radius_miles": 800,
            "naics_codes": ["493120", "484110", "493110"], "uei": "SCL8N3P5Q2W7",
            "services_description": "Temperature-controlled logistics across the Southeast US. Fleet of 50+ refrigerated trucks with real-time tracking.",
            "past_performance": [
                {"contract": "Southeast Regional Cold Chain", "agency": "USDA AMS", "value": 890000, "year": 2024, "description": "Managed cold chain logistics for 8-state region."},
                {"contract": "GA Emergency Food Distribution", "agency": "FEMA Region 4", "value": 520000, "year": 2023, "description": "Rapid deployment of refrigerated transport during severe weather."},
            ],
            "annual_revenue": 12500000, "employee_count": 120, "years_in_business": 18, "small_business": False,
        },
        {
            "name": "Great Lakes Cold Storage Inc",
            "org_type": "distributor",
            "description": "Industrial cold storage and distribution facility in Detroit. 100,000 sq ft facility.",
            "zip_code": "48201", "lat": 42.3486, "lng": -83.0567,
            "contact_email": "info@greatlakescold.com",
            "capabilities": ["cold storage", "warehouse distribution", "refrigerated transport", "infrastructure"],
            "certifications": ["USDA", "SQF Certified"],
            "service_radius_miles": 600,
            "naics_codes": ["493120", "493110", "484110"], "uei": "GLC9T5W2K7R4",
            "services_description": "Industrial-scale cold storage and frozen food distribution serving the Great Lakes region.",
            "past_performance": [
                {"contract": "MI Cold Storage Network", "agency": "Michigan DHHS", "value": 620000, "year": 2024, "description": "Stored and distributed 8M lbs of frozen commodity foods."},
                {"contract": "Great Lakes TEFAP Storage", "agency": "USDA FNS", "value": 480000, "year": 2023, "description": "Cold storage management for TEFAP commodities."},
            ],
            "annual_revenue": 7800000, "employee_count": 65, "years_in_business": 25, "small_business": False,
        },
        {
            "name": "East Coast Fresh Distributors",
            "org_type": "distributor",
            "description": "Full-service produce distributor serving the Eastern seaboard.",
            "zip_code": "19101", "lat": 39.9526, "lng": -75.1652,
            "contact_email": "sales@eastcoastfresh.com",
            "capabilities": ["fresh produce", "refrigerated transport", "local sourcing", "last mile delivery", "institutional food service"],
            "certifications": ["USDA", "GAP Certified"],
            "service_radius_miles": 800,
            "naics_codes": ["424480", "484110", "493110"], "uei": "ECF3W7K9R5N1",
            "services_description": "Full-service produce distribution from Florida to Maine. Direct farm relationships with 200+ growers.",
            "past_performance": [
                {"contract": "Northeast School Produce", "agency": "USDA AMS", "value": 2200000, "year": 2024, "description": "Supplied fresh produce to 400+ schools across 5 states."},
                {"contract": "PA Farm-to-Food Bank", "agency": "PA Dept of Agriculture", "value": 580000, "year": 2023, "description": "Connected 85 local farms to 120 food bank distribution points."},
            ],
            "annual_revenue": 18500000, "employee_count": 165, "years_in_business": 30, "small_business": False,
        },
        {
            "name": "Gulf Coast Emergency Services",
            "org_type": "distributor",
            "description": "Emergency logistics provider specializing in disaster food relief along the Gulf Coast.",
            "zip_code": "77001", "lat": 29.7604, "lng": -95.3698,
            "contact_email": "dispatch@gulfcoastemergency.com",
            "capabilities": ["emergency supply", "disaster relief", "shelf-stable goods", "last mile delivery", "warehouse distribution"],
            "certifications": ["FEMA vendor", "USDA"],
            "service_radius_miles": 800,
            "naics_codes": ["493110", "484110", "561210"], "uei": "GCE8P4L2M6W3",
            "services_description": "Rapid-response emergency logistics for Gulf Coast disaster zones. Pre-positioned staging areas and 24-hour mobilization.",
            "past_performance": [
                {"contract": "Hurricane Season Response", "agency": "FEMA Region 6", "value": 950000, "year": 2024, "description": "Deployed emergency food relief for 3 hurricanes."},
                {"contract": "TX Flood Relief Logistics", "agency": "Texas TDEM", "value": 620000, "year": 2023, "description": "Emergency food and water distribution to 15 flood-affected counties."},
            ],
            "annual_revenue": 11200000, "employee_count": 95, "years_in_business": 16, "small_business": False,
        },
        {
            "name": "Buckeye Harvest Hub",
            "org_type": "distributor",
            "description": "Ohio food hub connecting small farms to institutional buyers and food banks.",
            "zip_code": "44101", "lat": 41.4993, "lng": -81.6944,
            "contact_email": "orders@buckeyeharvesthub.com",
            "capabilities": ["food hub operations", "local sourcing", "fresh produce", "warehouse distribution", "refrigerated transport"],
            "certifications": ["USDA", "GAP Certified", "Small Business"],
            "service_radius_miles": 500,
            "naics_codes": ["424480", "493110", "424490"], "uei": "BHH2M6K4V8R1",
            "services_description": "Regional food hub aggregating from 150+ small farms for institutional and food bank buyers.",
            "past_performance": [
                {"contract": "Ohio Food Hub Network", "agency": "USDA AMS", "value": 450000, "year": 2024, "description": "Aggregated and distributed 3.5M lbs from 150 farms."},
                {"contract": "Cleveland Farm-to-Table", "agency": "OH Dept of Agriculture", "value": 275000, "year": 2023, "description": "School and hospital produce supply program."},
            ],
            "annual_revenue": 5200000, "employee_count": 48, "years_in_business": 10, "small_business": True,
        },
        {
            "name": "Sunshine State Logistics",
            "org_type": "distributor",
            "description": "Florida food logistics company with temperature-controlled fleet serving the entire state.",
            "zip_code": "32099", "lat": 30.3322, "lng": -81.6557,
            "contact_email": "logistics@sunshinestatelog.com",
            "capabilities": ["refrigerated transport", "last mile delivery", "warehouse distribution", "emergency supply", "SNAP distribution"],
            "certifications": ["USDA", "Small Business"],
            "service_radius_miles": 600,
            "naics_codes": ["484110", "493110", "492210"], "uei": "SSL6W4P8K3M2",
            "services_description": "Statewide food logistics with temperature-controlled fleet. Last-mile delivery to food banks and social service agencies.",
            "past_performance": [
                {"contract": "FL Food Bank Logistics", "agency": "Florida DCF", "value": 430000, "year": 2024, "description": "Statewide food bank distribution serving 2M+ individuals."},
                {"contract": "Hurricane Ian Food Relief", "agency": "FEMA Region 4", "value": 380000, "year": 2023, "description": "Emergency food distribution to 8 hurricane-affected counties."},
            ],
            "annual_revenue": 6200000, "employee_count": 72, "years_in_business": 19, "small_business": False,
        },
        {
            "name": "Midwest Express Transport",
            "org_type": "distributor",
            "description": "Refrigerated freight carrier specializing in food distribution across the Midwest and Great Plains.",
            "zip_code": "64101", "lat": 39.0997, "lng": -94.5786,
            "contact_email": "dispatch@midwestexpress.com",
            "capabilities": ["refrigerated transport", "warehouse distribution", "cold storage", "last mile delivery", "food hub operations"],
            "certifications": ["USDA", "FDA", "Small Business"],
            "service_radius_miles": 1000,
            "naics_codes": ["484110", "493120", "493110"], "uei": "MET7K3R5N2W4",
            "services_description": "LTL and FTL refrigerated freight across 12 Midwest states. Cross-dock facilities in KC, St. Louis, Minneapolis, and Chicago.",
            "past_performance": [
                {"contract": "USDA Commodity Transport", "agency": "USDA FNS", "value": 920000, "year": 2024, "description": "Transported 12M lbs USDA commodities across 8 states."},
                {"contract": "Midwest Food Bank Network", "agency": "Feeding America", "value": 680000, "year": 2023, "description": "Weekly distribution routes to 90 food bank locations."},
            ],
            "annual_revenue": 14500000, "employee_count": 130, "years_in_business": 24, "small_business": False,
        },
        {
            "name": "Carolina Distribution Co",
            "org_type": "distributor",
            "description": "Full-service food distribution serving North and South Carolina with focus on institutional and nonprofit clients.",
            "zip_code": "28201", "lat": 35.2271, "lng": -80.8431,
            "contact_email": "sales@carolinadist.com",
            "capabilities": ["warehouse distribution", "refrigerated transport", "last mile delivery", "institutional food service", "fresh produce"],
            "certifications": ["USDA", "GAP Certified", "Small Business"],
            "service_radius_miles": 500,
            "naics_codes": ["424480", "484110", "493110"], "uei": "CDC5M8K3R7N2",
            "services_description": "Regional food distribution hub. 60,000 sq ft warehouse with cold storage. Serves 300+ institutional and nonprofit clients.",
            "past_performance": [
                {"contract": "NC School Nutrition Logistics", "agency": "NC DPI", "value": 520000, "year": 2024, "description": "Food distribution to 180 schools across 12 counties."},
                {"contract": "SC Food Bank Transport", "agency": "Feeding America", "value": 310000, "year": 2023, "description": "Weekly refrigerated transport to 45 food bank sites."},
            ],
            "annual_revenue": 8200000, "employee_count": 75, "years_in_business": 15, "small_business": True,
        },
        {
            "name": "Southwest Rapid Logistics",
            "org_type": "distributor",
            "description": "Emergency and routine food distribution across AZ, NM, and West TX with bilingual operations.",
            "zip_code": "85001", "lat": 33.4484, "lng": -112.0740,
            "contact_email": "ops@swrapidlogistics.com",
            "capabilities": ["emergency supply", "last mile delivery", "warehouse distribution", "refrigerated transport", "rural outreach"],
            "certifications": ["FEMA vendor", "USDA", "HUBZone"],
            "service_radius_miles": 800,
            "naics_codes": ["484110", "493110", "561210"], "uei": "SRL4N7K2M8R5",
            "services_description": "Bilingual food logistics operation. Emergency deployment capability with 40+ trucks. Serves tribal and border communities.",
            "past_performance": [
                {"contract": "AZ Emergency Food Deployment", "agency": "FEMA Region 9", "value": 580000, "year": 2024, "description": "Emergency food distribution to 8 tribal communities during heat emergency."},
                {"contract": "NM Rural Food Access", "agency": "NM Human Services", "value": 340000, "year": 2023, "description": "Monthly food delivery to 22 remote communities."},
            ],
            "annual_revenue": 6800000, "employee_count": 62, "years_in_business": 12, "small_business": True,
        },
        # ── NONPROFITS (IDs 23–32) ──────────────────
        {
            "name": "Mid-South Food Bank Alliance",
            "org_type": "nonprofit",
            "description": "Network of food banks serving Tennessee, Mississippi, and Arkansas. Operates 12 distribution centers.",
            "zip_code": "38103", "lat": 35.1495, "lng": -90.0490,
            "contact_email": "info@midsouthfoodbank.org",
            "capabilities": ["warehouse distribution", "last mile delivery", "community nutrition", "USDA commodities", "mobile food pantry"],
            "certifications": ["Feeding America", "USDA"],
            "service_radius_miles": 500,
            "naics_codes": ["624210", "493110", "624190"], "uei": "MSF6R2T8V4K1",
            "services_description": "Tri-state food bank network. Coordinates emergency food distribution, USDA commodity programs, and mobile food pantry operations.",
            "past_performance": [
                {"contract": "TEFAP Distribution", "agency": "USDA FNS", "value": 1200000, "year": 2024, "description": "Distributed 15M lbs of TEFAP commodities to 500,000+ individuals."},
                {"contract": "Delta Flood Response", "agency": "FEMA", "value": 450000, "year": 2023, "description": "Emergency food distribution to 12 counties during Mississippi River flooding."},
            ],
            "annual_revenue": 8500000, "employee_count": 85, "years_in_business": 22, "small_business": False,
        },
        {
            "name": "Community Harvest Network",
            "org_type": "nonprofit",
            "description": "Food rescue organization recovering surplus food from farms, restaurants, and grocers.",
            "zip_code": "37203", "lat": 36.1627, "lng": -86.7816,
            "contact_email": "hello@communityharvestnetwork.org",
            "capabilities": ["food rescue", "fresh produce", "community nutrition", "local sourcing", "warehouse distribution"],
            "certifications": ["Feeding America", "USDA"],
            "service_radius_miles": 500,
            "naics_codes": ["624210", "424480", "562219"], "uei": "CHN5V3J7M1Q4",
            "services_description": "Food rescue and redistribution. 10M+ lbs annually redistributed to food-insecure communities.",
            "past_performance": [
                {"contract": "TN Food Rescue Initiative", "agency": "TN Dept of Agriculture", "value": 350000, "year": 2024, "description": "Rescued 4.2M lbs of surplus food from 120 partners."},
                {"contract": "SE Farm Gleaning Program", "agency": "USDA AMS", "value": 280000, "year": 2023, "description": "Coordinated gleaning operations across 45 farms."},
            ],
            "annual_revenue": 3200000, "employee_count": 38, "years_in_business": 9, "small_business": True,
        },
        {
            "name": "Nourish Chicago",
            "org_type": "nonprofit",
            "description": "Chicago-based nonprofit operating mobile food pantries and community kitchens.",
            "zip_code": "60621", "lat": 41.7795, "lng": -87.6424,
            "contact_email": "partners@nourishchicago.org",
            "capabilities": ["mobile food pantry", "community nutrition", "meal preparation", "culinary training", "fresh produce"],
            "certifications": ["Feeding America", "SBA 8(a)"],
            "service_radius_miles": 300,
            "naics_codes": ["624210", "624190", "722514"], "uei": "NCH4L8M3P6W2",
            "services_description": "Urban food access nonprofit operating 8 mobile food pantries and 3 community kitchens.",
            "past_performance": [
                {"contract": "Chicago Food Desert Initiative", "agency": "City of Chicago DFSS", "value": 1500000, "year": 2024, "description": "Mobile markets and community kitchens serving 50,000 households."},
                {"contract": "IL SNAP Outreach", "agency": "Illinois DHS", "value": 320000, "year": 2023, "description": "SNAP enrollment assistance for 8,400 new participants."},
            ],
            "annual_revenue": 5600000, "employee_count": 72, "years_in_business": 11, "small_business": True,
        },
        {
            "name": "Pueblo Food Sovereignty Project",
            "org_type": "nonprofit",
            "description": "Indigenous-led organization supporting food sovereignty across New Mexico Pueblo communities.",
            "zip_code": "87101", "lat": 35.0844, "lng": -106.6504,
            "contact_email": "info@pueblofoodsovereignty.org",
            "capabilities": ["cultural food programs", "food preservation", "community nutrition", "rural outreach"],
            "certifications": ["Indian Economic Enterprise", "USDA"],
            "service_radius_miles": 400,
            "naics_codes": ["624210", "311999", "624190"], "uei": "PFS7N2K5R3J8",
            "services_description": "Indigenous food sovereignty: traditional food preservation, seed saving, community gardens, and FDPIR distribution.",
            "past_performance": [
                {"contract": "NM Tribal Food Distribution", "agency": "USDA FNS FDPIR", "value": 420000, "year": 2024, "description": "Monthly food packages to 3,200 households across 8 Pueblo communities."},
                {"contract": "Indigenous Food Systems", "agency": "USDA NIFA", "value": 180000, "year": 2023, "description": "Traditional food preservation training and seed bank development."},
            ],
            "annual_revenue": 2100000, "employee_count": 28, "years_in_business": 7, "small_business": True,
        },
        {
            "name": "Baltimore Community Kitchen Collective",
            "org_type": "nonprofit",
            "description": "Shared commercial kitchen and food entrepreneur incubator in East Baltimore.",
            "zip_code": "21201", "lat": 39.2904, "lng": -76.6122,
            "contact_email": "info@bmorekitchen.org",
            "capabilities": ["culinary training", "community nutrition", "food hub operations", "meal preparation"],
            "certifications": ["SBA 8(a)", "Maryland MBE"],
            "service_radius_miles": 200,
            "naics_codes": ["722514", "611699", "624190"], "uei": "BCK5R3N7T2J4",
            "services_description": "Shared commercial kitchen supporting 40+ BIPOC food entrepreneurs with training, kitchen access, and community meal programs.",
            "past_performance": [
                {"contract": "Baltimore Food Incubator", "agency": "Baltimore Development Corp", "value": 600000, "year": 2024, "description": "Supported 42 food businesses, created 85 jobs."},
                {"contract": "MD Culinary Training", "agency": "Maryland DLLR", "value": 280000, "year": 2023, "description": "Workforce development. 92% job placement rate for 120 graduates."},
            ],
            "annual_revenue": 2800000, "employee_count": 32, "years_in_business": 6, "small_business": True,
        },
        {
            "name": "Carolina Nutrition Partners",
            "org_type": "nonprofit",
            "description": "NC/SC nutrition nonprofit providing community nutrition education and farmers market SNAP matching.",
            "zip_code": "28201", "lat": 35.2271, "lng": -80.8431,
            "contact_email": "programs@carolinanutrition.org",
            "capabilities": ["community nutrition", "culinary training", "farmers market", "SNAP distribution"],
            "certifications": ["Feeding America"],
            "service_radius_miles": 400,
            "naics_codes": ["624190", "611699", "624210"], "uei": "CNP4J8M2R6W3",
            "services_description": "Farmers market SNAP matching, community cooking classes, and nutrition counseling across NC and SC.",
            "past_performance": [
                {"contract": "NC SNAP Double Bucks", "agency": "NC DHHS", "value": 240000, "year": 2024, "description": "SNAP incentive program at 45 farmers markets."},
                {"contract": "SC Nutrition Education", "agency": "USDA SNAP-Ed", "value": 180000, "year": 2023, "description": "Nutrition education reaching 15,000 participants."},
            ],
            "annual_revenue": 1800000, "employee_count": 22, "years_in_business": 8, "small_business": True,
        },
        {
            "name": "Appalachian Food Network",
            "org_type": "nonprofit",
            "description": "Regional nonprofit fighting food insecurity in Appalachian communities across KY, TN, and VA.",
            "zip_code": "42101", "lat": 36.9903, "lng": -86.4436,
            "contact_email": "connect@appfoodnetwork.org",
            "capabilities": ["mobile food pantry", "rural outreach", "meal preparation", "institutional food service", "community nutrition"],
            "certifications": ["Feeding America", "HUBZone", "USDA"],
            "service_radius_miles": 500,
            "naics_codes": ["624210", "722310", "624190"], "uei": "AFN3R7K5M2W4",
            "services_description": "Mobile markets, summer feeding, and community food distribution serving rural Appalachian communities.",
            "past_performance": [
                {"contract": "Appalachian SFSP", "agency": "Kentucky DOE", "value": 410000, "year": 2024, "description": "Summer feeding at 35 sites reaching 8,000 children."},
                {"contract": "Rural Food Access", "agency": "USDA RD", "value": 320000, "year": 2023, "description": "Mobile market program serving 22 rural communities."},
            ],
            "annual_revenue": 2400000, "employee_count": 30, "years_in_business": 13, "small_business": True,
        },
        {
            "name": "Miami-Dade Food Rescue Alliance",
            "org_type": "nonprofit",
            "description": "South Florida food rescue and redistribution network serving Miami-Dade County communities.",
            "zip_code": "33101", "lat": 25.7617, "lng": -80.1918,
            "contact_email": "info@mdfooodrescue.org",
            "capabilities": ["food rescue", "community nutrition", "warehouse distribution", "last mile delivery", "fresh produce"],
            "certifications": ["Feeding America", "USDA", "Small Business"],
            "service_radius_miles": 300,
            "naics_codes": ["624210", "562219", "493110"], "uei": "MFR8K3N5R2W4",
            "services_description": "Food recovery from 200+ restaurants, grocers, and farms. Redistributes 6M lbs annually to 80 community organizations.",
            "past_performance": [
                {"contract": "Miami-Dade Food Recovery", "agency": "Miami-Dade County", "value": 520000, "year": 2024, "description": "Recovered 6M lbs of food, served 120,000 individuals."},
                {"contract": "FL Hurricane Food Response", "agency": "FEMA Region 4", "value": 280000, "year": 2023, "description": "Emergency food distribution during hurricane season."},
            ],
            "annual_revenue": 3400000, "employee_count": 40, "years_in_business": 8, "small_business": True,
        },
        {
            "name": "DC Hunger Solutions",
            "org_type": "nonprofit",
            "description": "Washington DC nonprofit providing nutrition education, food distribution, and policy advocacy.",
            "zip_code": "20001", "lat": 38.9072, "lng": -77.0369,
            "contact_email": "info@dchungersolutions.org",
            "capabilities": ["community nutrition", "culinary training", "SNAP distribution", "mobile food pantry", "rural outreach"],
            "certifications": ["Feeding America", "SBA 8(a)"],
            "service_radius_miles": 200,
            "naics_codes": ["624210", "611699", "624190"], "uei": "DHS6M4K8R3N2",
            "services_description": "Food access programs across DC Wards 7 & 8. Operates community kitchens, SNAP outreach, and mobile markets.",
            "past_performance": [
                {"contract": "DC Nutrition Education", "agency": "DC Dept of Health", "value": 165000, "year": 2024, "description": "Nutrition and cooking classes at 25 community sites."},
                {"contract": "Ward 8 Food Access", "agency": "DC Office of Planning", "value": 220000, "year": 2023, "description": "Mobile market and SNAP enrollment serving 12,000 residents."},
            ],
            "annual_revenue": 1900000, "employee_count": 24, "years_in_business": 10, "small_business": True,
        },
    ]

    for o in orgs:
        db.session.add(Organization(**o))


def seed_emergency_capacities():
    today = date.today()
    caps = [
        # Supplier 1: Delta Fresh Foods Co-op
        {"organization_id": 1, "supply_type": "fresh_produce", "item_name": "Fresh Leafy Greens",
         "quantity": 5000, "unit": "lbs", "unit_cost": 2.50, "zip_code": "38701",
         "lat": 33.4015, "lng": -91.0618, "service_radius_miles": 500,
         "available_date": today, "expiry_date": today + timedelta(days=14)},
        {"organization_id": 1, "supply_type": "fresh_produce", "item_name": "Mixed Fruit Cases",
         "quantity": 2000, "unit": "cases", "unit_cost": 18.00, "zip_code": "38701",
         "lat": 33.4015, "lng": -91.0618, "service_radius_miles": 500,
         "available_date": today, "expiry_date": today + timedelta(days=10)},
        {"organization_id": 1, "supply_type": "fresh_produce", "item_name": "Root Vegetables (carrots, potatoes, onions)",
         "quantity": 8000, "unit": "lbs", "unit_cost": 1.80, "zip_code": "38701",
         "lat": 33.4015, "lng": -91.0618, "service_radius_miles": 500,
         "available_date": today, "expiry_date": today + timedelta(days=21)},
        # Supplier 2: Bayou Provisions LLC
        {"organization_id": 2, "supply_type": "shelf_stable", "item_name": "MRE Ration Packs",
         "quantity": 15000, "unit": "meals", "unit_cost": 8.50, "zip_code": "70112",
         "lat": 29.9511, "lng": -90.0715, "service_radius_miles": 600,
         "available_date": today, "expiry_date": today + timedelta(days=365)},
        {"organization_id": 2, "supply_type": "water", "item_name": "Bottled Water (16oz)",
         "quantity": 50000, "unit": "units", "unit_cost": 0.35, "zip_code": "70112",
         "lat": 29.9511, "lng": -90.0715, "service_radius_miles": 600,
         "available_date": today, "expiry_date": today + timedelta(days=730)},
        {"organization_id": 2, "supply_type": "non_perishable", "item_name": "Canned Soup Cases",
         "quantity": 8000, "unit": "cans", "unit_cost": 1.80, "zip_code": "70112",
         "lat": 29.9511, "lng": -90.0715, "service_radius_miles": 600,
         "available_date": today, "expiry_date": today + timedelta(days=540)},
        {"organization_id": 2, "supply_type": "non_perishable", "item_name": "Peanut Butter (18oz jars)",
         "quantity": 6000, "unit": "jars", "unit_cost": 3.50, "zip_code": "70112",
         "lat": 29.9511, "lng": -90.0715, "service_radius_miles": 600,
         "available_date": today, "expiry_date": today + timedelta(days=365)},
        {"organization_id": 2, "supply_type": "water", "item_name": "Water Pallets (1 Gallon)",
         "quantity": 25000, "unit": "gallons", "unit_cost": 1.20, "zip_code": "70112",
         "lat": 29.9511, "lng": -90.0715, "service_radius_miles": 600,
         "available_date": today, "expiry_date": today + timedelta(days=730)},
        # Supplier 3: Heartland Meal Services
        {"organization_id": 3, "supply_type": "non_perishable", "item_name": "Shelf-Stable Meal Kits",
         "quantity": 10000, "unit": "meals", "unit_cost": 4.50, "zip_code": "46201",
         "lat": 39.7684, "lng": -86.1581, "service_radius_miles": 600,
         "available_date": today, "expiry_date": today + timedelta(days=180)},
        {"organization_id": 3, "supply_type": "non_perishable", "item_name": "Senior Nutrition Meal Packs",
         "quantity": 5000, "unit": "meals", "unit_cost": 5.25, "zip_code": "46201",
         "lat": 39.7684, "lng": -86.1581, "service_radius_miles": 600,
         "available_date": today, "expiry_date": today + timedelta(days=120)},
        # Supplier 5: Lone Star Food Systems
        {"organization_id": 5, "supply_type": "non_perishable", "item_name": "Freeze-Dried Ration Packs",
         "quantity": 20000, "unit": "meals", "unit_cost": 6.00, "zip_code": "75201",
         "lat": 32.7872, "lng": -96.7985, "service_radius_miles": 800,
         "available_date": today, "expiry_date": today + timedelta(days=730)},
        {"organization_id": 5, "supply_type": "canned_goods", "item_name": "USDA Commodity Canned Meat",
         "quantity": 12000, "unit": "cans", "unit_cost": 2.50, "zip_code": "75201",
         "lat": 32.7872, "lng": -96.7985, "service_radius_miles": 800,
         "available_date": today, "expiry_date": today + timedelta(days=365)},
        {"organization_id": 5, "supply_type": "shelf_stable", "item_name": "Canned Vegetables (mixed)",
         "quantity": 15000, "unit": "cans", "unit_cost": 1.40, "zip_code": "75201",
         "lat": 32.7872, "lng": -96.7985, "service_radius_miles": 800,
         "available_date": today, "expiry_date": today + timedelta(days=540)},
        {"organization_id": 5, "supply_type": "water", "item_name": "Emergency Water Jugs (5 gal)",
         "quantity": 8000, "unit": "jugs", "unit_cost": 4.50, "zip_code": "75201",
         "lat": 32.7872, "lng": -96.7985, "service_radius_miles": 800,
         "available_date": today, "expiry_date": today + timedelta(days=730)},
        # Supplier 6: Midwest Senior Nutrition
        {"organization_id": 6, "supply_type": "medical_nutrition", "item_name": "Ensure/Boost Nutrition Shakes",
         "quantity": 5000, "unit": "units", "unit_cost": 8.00, "zip_code": "53201",
         "lat": 43.0389, "lng": -87.9065, "service_radius_miles": 500,
         "available_date": today, "expiry_date": today + timedelta(days=120)},
        {"organization_id": 6, "supply_type": "baby_formula", "item_name": "Infant Formula (12oz cans)",
         "quantity": 2000, "unit": "cans", "unit_cost": 18.00, "zip_code": "53201",
         "lat": 43.0389, "lng": -87.9065, "service_radius_miles": 500,
         "available_date": today, "expiry_date": today + timedelta(days=180)},
        {"organization_id": 6, "supply_type": "medical_nutrition", "item_name": "Diabetic Meal Replacement Shakes",
         "quantity": 3000, "unit": "units", "unit_cost": 9.50, "zip_code": "53201",
         "lat": 43.0389, "lng": -87.9065, "service_radius_miles": 500,
         "available_date": today, "expiry_date": today + timedelta(days=90)},
        # Supplier 7: Sooner State Food Co-op
        {"organization_id": 7, "supply_type": "non_perishable", "item_name": "Traditional Cornmeal & Flour",
         "quantity": 4000, "unit": "lbs", "unit_cost": 2.00, "zip_code": "73101",
         "lat": 35.4676, "lng": -97.5164, "service_radius_miles": 600,
         "available_date": today, "expiry_date": today + timedelta(days=180)},
        {"organization_id": 7, "supply_type": "canned_goods", "item_name": "USDA Commodity Canned Fruit",
         "quantity": 6000, "unit": "cans", "unit_cost": 1.60, "zip_code": "73101",
         "lat": 35.4676, "lng": -97.5164, "service_radius_miles": 600,
         "available_date": today, "expiry_date": today + timedelta(days=365)},
        # Supplier 8: Pacific Coast Organics
        {"organization_id": 8, "supply_type": "fresh_produce", "item_name": "Organic Citrus Mix",
         "quantity": 10000, "unit": "lbs", "unit_cost": 2.80, "zip_code": "90011",
         "lat": 33.9425, "lng": -118.2551, "service_radius_miles": 800,
         "available_date": today, "expiry_date": today + timedelta(days=14)},
        {"organization_id": 8, "supply_type": "fresh_produce", "item_name": "Seasonal Organic Vegetables",
         "quantity": 7000, "unit": "lbs", "unit_cost": 3.00, "zip_code": "90011",
         "lat": 33.9425, "lng": -118.2551, "service_radius_miles": 800,
         "available_date": today, "expiry_date": today + timedelta(days=10)},
        # Supplier 9: Northeast Emergency Provisions
        {"organization_id": 9, "supply_type": "shelf_stable", "item_name": "Emergency Food Pallets",
         "quantity": 200, "unit": "pallets", "unit_cost": 450.00, "zip_code": "10451",
         "lat": 40.8207, "lng": -73.9234, "service_radius_miles": 700,
         "available_date": today, "expiry_date": today + timedelta(days=365)},
        {"organization_id": 9, "supply_type": "water", "item_name": "Emergency Water Cases (24-pack)",
         "quantity": 30000, "unit": "cases", "unit_cost": 5.00, "zip_code": "10451",
         "lat": 40.8207, "lng": -73.9234, "service_radius_miles": 700,
         "available_date": today, "expiry_date": today + timedelta(days=730)},
        {"organization_id": 9, "supply_type": "non_perishable", "item_name": "Canned Beans (15oz)",
         "quantity": 20000, "unit": "cans", "unit_cost": 1.20, "zip_code": "10451",
         "lat": 40.8207, "lng": -73.9234, "service_radius_miles": 700,
         "available_date": today, "expiry_date": today + timedelta(days=540)},
        {"organization_id": 9, "supply_type": "non_perishable", "item_name": "Rice (25lb bags)",
         "quantity": 5000, "unit": "bags", "unit_cost": 12.00, "zip_code": "10451",
         "lat": 40.8207, "lng": -73.9234, "service_radius_miles": 700,
         "available_date": today, "expiry_date": today + timedelta(days=365)},
        # Supplier 10: Dixie Farms Fresh
        {"organization_id": 10, "supply_type": "fresh_produce", "item_name": "Seasonal Produce Mix",
         "quantity": 8000, "unit": "lbs", "unit_cost": 2.00, "zip_code": "30901",
         "lat": 33.4735, "lng": -81.9748, "service_radius_miles": 500,
         "available_date": today, "expiry_date": today + timedelta(days=7)},
        {"organization_id": 10, "supply_type": "fresh_produce", "item_name": "Sweet Potatoes",
         "quantity": 6000, "unit": "lbs", "unit_cost": 1.50, "zip_code": "30901",
         "lat": 33.4735, "lng": -81.9748, "service_radius_miles": 500,
         "available_date": today, "expiry_date": today + timedelta(days=30)},
        # Supplier 11: Heartland Grain & Staples
        {"organization_id": 11, "supply_type": "non_perishable", "item_name": "Bulk Rice (50lb bags)",
         "quantity": 10000, "unit": "bags", "unit_cost": 22.00, "zip_code": "50301",
         "lat": 41.5868, "lng": -93.6250, "service_radius_miles": 800,
         "available_date": today, "expiry_date": today + timedelta(days=365)},
        {"organization_id": 11, "supply_type": "non_perishable", "item_name": "Dried Beans (25lb bags)",
         "quantity": 8000, "unit": "bags", "unit_cost": 18.00, "zip_code": "50301",
         "lat": 41.5868, "lng": -93.6250, "service_radius_miles": 800,
         "available_date": today, "expiry_date": today + timedelta(days=365)},
        {"organization_id": 11, "supply_type": "non_perishable", "item_name": "Oatmeal (42oz containers)",
         "quantity": 5000, "unit": "units", "unit_cost": 4.50, "zip_code": "50301",
         "lat": 41.5868, "lng": -93.6250, "service_radius_miles": 800,
         "available_date": today, "expiry_date": today + timedelta(days=270)},
        # Supplier 12: Border Fresh Produce
        {"organization_id": 12, "supply_type": "fresh_produce", "item_name": "Fresh Peppers & Tomatoes",
         "quantity": 6000, "unit": "lbs", "unit_cost": 2.20, "zip_code": "79901",
         "lat": 31.7619, "lng": -106.4850, "service_radius_miles": 500,
         "available_date": today, "expiry_date": today + timedelta(days=10)},
        {"organization_id": 12, "supply_type": "fresh_produce", "item_name": "Avocados (cases)",
         "quantity": 1500, "unit": "cases", "unit_cost": 28.00, "zip_code": "79901",
         "lat": 31.7619, "lng": -106.4850, "service_radius_miles": 500,
         "available_date": today, "expiry_date": today + timedelta(days=7)},
        # Distributors with capacity
        {"organization_id": 16, "supply_type": "shelf_stable", "item_name": "Emergency Food Staging (pre-positioned)",
         "quantity": 100, "unit": "pallets", "unit_cost": 500.00, "zip_code": "77001",
         "lat": 29.7604, "lng": -95.3698, "service_radius_miles": 800,
         "available_date": today, "expiry_date": today + timedelta(days=365)},
        {"organization_id": 16, "supply_type": "water", "item_name": "Emergency Water Reserve",
         "quantity": 40000, "unit": "gallons", "unit_cost": 1.10, "zip_code": "77001",
         "lat": 29.7604, "lng": -95.3698, "service_radius_miles": 800,
         "available_date": today, "expiry_date": today + timedelta(days=730)},
        {"organization_id": 14, "supply_type": "dairy", "item_name": "UHT Milk Cases",
         "quantity": 3000, "unit": "cases", "unit_cost": 24.00, "zip_code": "48201",
         "lat": 42.3486, "lng": -83.0567, "service_radius_miles": 600,
         "available_date": today, "expiry_date": today + timedelta(days=90)},
        {"organization_id": 15, "supply_type": "fresh_produce", "item_name": "East Coast Seasonal Mix",
         "quantity": 12000, "unit": "lbs", "unit_cost": 2.00, "zip_code": "19101",
         "lat": 39.9526, "lng": -75.1652, "service_radius_miles": 800,
         "available_date": today, "expiry_date": today + timedelta(days=7)},
        {"organization_id": 19, "supply_type": "hygiene_supplies", "item_name": "Emergency Hygiene Kits",
         "quantity": 3000, "unit": "kits", "unit_cost": 8.50, "zip_code": "32099",
         "lat": 30.3322, "lng": -81.6557, "service_radius_miles": 600,
         "available_date": today, "expiry_date": today + timedelta(days=365)},
        {"organization_id": 22, "supply_type": "water", "item_name": "Emergency Water Reserve (SW)",
         "quantity": 20000, "unit": "gallons", "unit_cost": 1.00, "zip_code": "85001",
         "lat": 33.4484, "lng": -112.0740, "service_radius_miles": 800,
         "available_date": today, "expiry_date": today + timedelta(days=730)},
        {"organization_id": 22, "supply_type": "non_perishable", "item_name": "Emergency Meal Packs (Southwest)",
         "quantity": 8000, "unit": "meals", "unit_cost": 5.00, "zip_code": "85001",
         "lat": 33.4484, "lng": -112.0740, "service_radius_miles": 800,
         "available_date": today, "expiry_date": today + timedelta(days=365)},
        {"organization_id": 20, "supply_type": "non_perishable", "item_name": "Bulk Pasta (10lb boxes)",
         "quantity": 4000, "unit": "boxes", "unit_cost": 8.00, "zip_code": "64101",
         "lat": 39.0997, "lng": -94.5786, "service_radius_miles": 1000,
         "available_date": today, "expiry_date": today + timedelta(days=365)},
        {"organization_id": 20, "supply_type": "canned_goods", "item_name": "Canned Tuna (6oz)",
         "quantity": 15000, "unit": "cans", "unit_cost": 1.50, "zip_code": "64101",
         "lat": 39.0997, "lng": -94.5786, "service_radius_miles": 1000,
         "available_date": today, "expiry_date": today + timedelta(days=730)},
    ]
    for c in caps:
        db.session.add(EmergencyCapacity(**c))


def seed_waste_reductions():
    records = [
        {"source_org_id": 24, "dest_org_id": 23, "supply_type": "fresh_produce",
         "item_name": "Rescued Farm Produce", "quantity_rescued": 45000, "unit": "lbs",
         "estimated_value": 67500, "source_zip": "37203", "dest_zip": "38103"},
        {"source_org_id": 15, "dest_org_id": 25, "supply_type": "fresh_produce",
         "item_name": "Surplus Grocery Produce", "quantity_rescued": 28000, "unit": "lbs",
         "estimated_value": 42000, "source_zip": "19101", "dest_zip": "60621"},
        {"source_org_id": 1, "dest_org_id": 23, "supply_type": "fresh_produce",
         "item_name": "Delta Region Surplus Harvest", "quantity_rescued": 35000, "unit": "lbs",
         "estimated_value": 52500, "source_zip": "38701", "dest_zip": "38614"},
        {"source_org_id": 5, "dest_org_id": 7, "supply_type": "canned_goods",
         "item_name": "Near-Expiry Canned Goods", "quantity_rescued": 20000, "unit": "cans",
         "estimated_value": 30000, "source_zip": "75201", "dest_zip": "73101"},
        {"source_org_id": 16, "dest_org_id": 19, "supply_type": "shelf_stable",
         "item_name": "Hurricane Season Surplus MREs", "quantity_rescued": 15000, "unit": "meals",
         "estimated_value": 75000, "source_zip": "77001", "dest_zip": "32099"},
        {"source_org_id": 14, "dest_org_id": 17, "supply_type": "dairy",
         "item_name": "Surplus Dairy Products", "quantity_rescued": 8000, "unit": "units",
         "estimated_value": 24000, "source_zip": "48201", "dest_zip": "44101"},
        {"source_org_id": 3, "dest_org_id": 29, "supply_type": "non_perishable",
         "item_name": "Institutional Meal Surplus", "quantity_rescued": 12000, "unit": "meals",
         "estimated_value": 36000, "source_zip": "46201", "dest_zip": "42101"},
        {"source_org_id": 2, "dest_org_id": 23, "supply_type": "water",
         "item_name": "Expiring Water Stock Rotation", "quantity_rescued": 10000, "unit": "gallons",
         "estimated_value": 12000, "source_zip": "70112", "dest_zip": "39201"},
        {"source_org_id": 8, "dest_org_id": 31, "supply_type": "fresh_produce",
         "item_name": "Surplus Organic Citrus", "quantity_rescued": 18000, "unit": "lbs",
         "estimated_value": 50400, "source_zip": "90011", "dest_zip": "85001"},
        {"source_org_id": 10, "dest_org_id": 28, "supply_type": "fresh_produce",
         "item_name": "Southeast Surplus Sweet Potatoes", "quantity_rescued": 22000, "unit": "lbs",
         "estimated_value": 33000, "source_zip": "30901", "dest_zip": "28201"},
        {"source_org_id": 11, "dest_org_id": 25, "supply_type": "non_perishable",
         "item_name": "Bulk Grain Overstock", "quantity_rescued": 30000, "unit": "lbs",
         "estimated_value": 45000, "source_zip": "50301", "dest_zip": "60621"},
        {"source_org_id": 9, "dest_org_id": 30, "supply_type": "shelf_stable",
         "item_name": "Near-Expiry Emergency Rations", "quantity_rescued": 8000, "unit": "meals",
         "estimated_value": 40000, "source_zip": "10451", "dest_zip": "21201"},
    ]
    for r in records:
        db.session.add(WasteReduction(**r))


if __name__ == "__main__":
    seed()
