"""Seed script for FoodMatch MVP database."""
import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from datetime import date, timedelta
from app import create_app, db
from app.models.solicitation import Solicitation
from app.models.organization import Organization
from app.models.zip_need_score import ZipNeedScore
from app.models.match_result import MatchResult


def seed():
    app = create_app()
    with app.app_context():
        print("Clearing existing data...")
        MatchResult.query.delete()
        Solicitation.query.delete()
        Organization.query.delete()
        ZipNeedScore.query.delete()
        db.session.commit()

        print("Seeding ZIP need scores...")
        seed_zip_scores()

        print("Seeding solicitations...")
        seed_solicitations()

        print("Seeding organizations...")
        seed_organizations()

        db.session.commit()
        print("Done! Seeded successfully.")


def seed_zip_scores():
    zips = [
        ("38601", 34.3668, -89.5195, "MS", "Abbeville", 0.28, 12000, 0.22, 82),
        ("38614", 33.7490, -90.7351, "MS", "Clarksdale", 0.31, 15000, 0.28, 89),
        ("38701", 33.4015, -91.0618, "MS", "Greenville", 0.29, 32000, 0.25, 85),
        ("72301", 35.2145, -90.1848, "AR", "West Memphis", 0.25, 25000, 0.21, 78),
        ("72401", 35.8423, -90.7043, "AR", "Jonesboro", 0.18, 75000, 0.14, 62),
        ("36601", 30.6944, -88.0431, "AL", "Mobile", 0.22, 190000, 0.19, 74),
        ("36104", 32.3668, -86.2999, "AL", "Montgomery", 0.21, 200000, 0.18, 72),
        ("30303", 33.7490, -84.3880, "GA", "Atlanta", 0.17, 500000, 0.13, 58),
        ("30901", 33.4735, -81.9748, "GA", "Augusta", 0.23, 200000, 0.20, 75),
        ("29401", 32.7765, -79.9311, "SC", "Charleston", 0.14, 140000, 0.10, 48),
        ("29201", 34.0007, -81.0348, "SC", "Columbia", 0.19, 135000, 0.15, 64),
        ("37203", 36.1627, -86.7816, "TN", "Nashville", 0.15, 690000, 0.11, 52),
        ("38103", 35.1495, -90.0490, "TN", "Memphis", 0.26, 650000, 0.23, 80),
        ("70112", 29.9511, -90.0715, "LA", "New Orleans", 0.24, 390000, 0.21, 77),
        ("70801", 30.4515, -91.1871, "LA", "Baton Rouge", 0.20, 225000, 0.17, 68),
        ("39201", 32.2988, -90.1848, "MS", "Jackson", 0.27, 170000, 0.24, 83),
        ("75201", 32.7872, -96.7985, "TX", "Dallas", 0.16, 1300000, 0.12, 55),
        ("77001", 29.7604, -95.3698, "TX", "Houston", 0.18, 2300000, 0.14, 60),
        ("85001", 33.4484, -112.0740, "AZ", "Phoenix", 0.17, 1700000, 0.13, 58),
        ("90011", 33.9425, -118.2551, "CA", "Los Angeles", 0.20, 55000, 0.17, 69),
        ("10451", 40.8207, -73.9234, "NY", "Bronx", 0.23, 45000, 0.20, 76),
        ("60621", 41.7795, -87.6424, "IL", "Chicago", 0.25, 35000, 0.22, 79),
        ("48201", 42.3486, -83.0567, "MI", "Detroit", 0.27, 40000, 0.24, 83),
        ("44101", 41.4993, -81.6944, "OH", "Cleveland", 0.24, 38000, 0.21, 77),
        ("21201", 39.2904, -76.6122, "MD", "Baltimore", 0.22, 42000, 0.19, 73),
        ("19101", 39.9526, -75.1652, "PA", "Philadelphia", 0.21, 55000, 0.18, 71),
        ("02101", 42.3601, -71.0589, "MA", "Boston", 0.13, 65000, 0.09, 45),
        ("33101", 25.7617, -80.1918, "FL", "Miami", 0.19, 470000, 0.15, 65),
        ("32099", 30.3322, -81.6557, "FL", "Jacksonville", 0.18, 950000, 0.14, 62),
        ("28201", 35.2271, -80.8431, "NC", "Charlotte", 0.16, 880000, 0.12, 55),
        ("27601", 35.7796, -78.6382, "NC", "Raleigh", 0.13, 475000, 0.09, 46),
        ("23219", 37.5407, -77.4360, "VA", "Richmond", 0.18, 230000, 0.14, 61),
        ("20001", 38.9072, -77.0369, "DC", "Washington", 0.15, 700000, 0.11, 52),
        ("63101", 38.6270, -90.1994, "MO", "St. Louis", 0.25, 300000, 0.22, 79),
        ("64101", 39.0997, -94.5786, "MO", "Kansas City", 0.19, 500000, 0.15, 64),
        ("55401", 44.9778, -93.2650, "MN", "Minneapolis", 0.14, 430000, 0.10, 48),
        ("53201", 43.0389, -87.9065, "WI", "Milwaukee", 0.22, 590000, 0.19, 73),
        ("46201", 39.7684, -86.1581, "IN", "Indianapolis", 0.19, 880000, 0.15, 64),
        ("40201", 38.2527, -85.7585, "KY", "Louisville", 0.20, 630000, 0.16, 67),
        ("73101", 35.4676, -97.5164, "OK", "Oklahoma City", 0.19, 680000, 0.15, 64),
        ("71101", 32.5252, -93.7502, "LA", "Shreveport", 0.24, 190000, 0.21, 77),
        ("79901", 31.7619, -106.4850, "TX", "El Paso", 0.22, 680000, 0.19, 73),
        ("87101", 35.0844, -106.6504, "NM", "Albuquerque", 0.20, 560000, 0.16, 67),
        ("29301", 34.9496, -81.9321, "SC", "Spartanburg", 0.21, 38000, 0.18, 70),
        ("31201", 32.8407, -83.6324, "GA", "Macon", 0.24, 153000, 0.21, 77),
        ("35801", 34.7304, -86.5861, "AL", "Huntsville", 0.15, 215000, 0.11, 51),
        ("37601", 36.3134, -82.3535, "TN", "Johnson City", 0.17, 67000, 0.13, 57),
        ("42101", 36.9903, -86.4436, "KY", "Bowling Green", 0.18, 75000, 0.14, 61),
        ("50301", 41.5868, -93.6250, "IA", "Des Moines", 0.15, 215000, 0.11, 52),
        ("68101", 41.2565, -95.9345, "NE", "Omaha", 0.16, 490000, 0.12, 55),
    ]
    for z in zips:
        db.session.add(ZipNeedScore(
            zip_code=z[0], lat=z[1], lng=z[2], state=z[3], city=z[4],
            food_insecurity_rate=z[5], population=z[6],
            snap_participation_rate=z[7], need_score=z[8],
        ))


def seed_solicitations():
    today = date.today()
    sols = [
        {
            "title": "USDA Fresh Produce Distribution - Mississippi Delta",
            "description": "Seeking suppliers for fresh fruit and vegetable distribution to food-insecure communities in the Mississippi Delta region. Must have cold chain capability and last-mile delivery experience.",
            "agency": "USDA Food and Nutrition Service",
            "naics_code": "311991",
            "set_aside_type": "Small Business",
            "zip_code": "38614",
            "lat": 33.7490, "lng": -90.7351,
            "categories": ["fresh produce", "cold storage", "last mile delivery"],
            "estimated_value": 450000, "status": "open",
            "posted_date": today - timedelta(days=5),
            "response_deadline": today + timedelta(days=25),
        },
        {
            "title": "School District Meal Program - Memphis Metro",
            "description": "Supply and deliver nutritious meals to 45 schools across the Memphis metropolitan area. Requires USDA compliance and experience with institutional food service.",
            "agency": "Memphis-Shelby County Schools",
            "naics_code": "722310",
            "set_aside_type": None,
            "zip_code": "38103",
            "lat": 35.1495, "lng": -90.0490,
            "categories": ["meal preparation", "institutional food service", "last mile delivery"],
            "estimated_value": 1200000, "status": "open",
            "posted_date": today - timedelta(days=10),
            "response_deadline": today + timedelta(days=20),
        },
        {
            "title": "Emergency Food Bank Supply Chain - New Orleans",
            "description": "Establish emergency food supply chain for disaster preparedness in New Orleans area food banks. Includes shelf-stable goods, cold storage, and distribution logistics.",
            "agency": "Louisiana Department of Agriculture",
            "naics_code": "493110",
            "set_aside_type": "8(a)",
            "zip_code": "70112",
            "lat": 29.9511, "lng": -90.0715,
            "categories": ["shelf-stable goods", "cold storage", "warehouse distribution", "emergency supply"],
            "estimated_value": 750000, "status": "open",
            "posted_date": today - timedelta(days=3),
            "response_deadline": today + timedelta(days=30),
        },
        {
            "title": "SNAP Distribution Technology Platform",
            "description": "Develop and manage electronic SNAP benefit distribution platform for rural Alabama communities. Must integrate with existing POS systems.",
            "agency": "Alabama Department of Human Resources",
            "naics_code": "541511",
            "set_aside_type": "HUBZone",
            "zip_code": "36601",
            "lat": 30.6944, "lng": -88.0431,
            "categories": ["SNAP distribution", "technology platform", "rural outreach"],
            "estimated_value": 320000, "status": "open",
            "posted_date": today - timedelta(days=7),
            "response_deadline": today + timedelta(days=35),
        },
        {
            "title": "Cold Chain Infrastructure - Atlanta Food Hub",
            "description": "Build and operate cold chain infrastructure for the Atlanta Regional Food Hub connecting local farms to food-insecure urban neighborhoods.",
            "agency": "Georgia Department of Agriculture",
            "naics_code": "493120",
            "set_aside_type": "Small Business",
            "zip_code": "30303",
            "lat": 33.7490, "lng": -84.3880,
            "categories": ["cold storage", "food hub operations", "local sourcing", "warehouse distribution"],
            "estimated_value": 890000, "status": "open",
            "posted_date": today - timedelta(days=2),
            "response_deadline": today + timedelta(days=28),
        },
        {
            "title": "Mobile Food Pantry Fleet - Rural Arkansas",
            "description": "Operate mobile food pantry vehicles serving rural communities in eastern Arkansas with limited grocery access. Weekly routes to 12 communities.",
            "agency": "Arkansas Department of Human Services",
            "naics_code": "624210",
            "set_aside_type": None,
            "zip_code": "72301",
            "lat": 35.2145, "lng": -90.1848,
            "categories": ["mobile food pantry", "last mile delivery", "rural outreach", "fresh produce"],
            "estimated_value": 280000, "status": "open",
            "posted_date": today - timedelta(days=8),
            "response_deadline": today + timedelta(days=22),
        },
        {
            "title": "USDA Commodity Distribution - South Carolina",
            "description": "Distribute USDA commodity foods to eligible households across 15 counties in South Carolina. Requires warehouse space and refrigerated transport.",
            "agency": "USDA Food Distribution Program",
            "naics_code": "493110",
            "set_aside_type": "Small Business",
            "zip_code": "29201",
            "lat": 34.0007, "lng": -81.0348,
            "categories": ["warehouse distribution", "refrigerated transport", "USDA commodities"],
            "estimated_value": 520000, "status": "open",
            "posted_date": today - timedelta(days=12),
            "response_deadline": today + timedelta(days=18),
        },
        {
            "title": "Farm to School Program - Nashville",
            "description": "Coordinate farm-to-school supply chain connecting Tennessee farms with Nashville area school cafeterias. Focus on fresh, locally-grown produce.",
            "agency": "Tennessee Department of Agriculture",
            "naics_code": "424480",
            "set_aside_type": None,
            "zip_code": "37203",
            "lat": 36.1627, "lng": -86.7816,
            "categories": ["local sourcing", "fresh produce", "institutional food service", "farm to school"],
            "estimated_value": 350000, "status": "open",
            "posted_date": today - timedelta(days=6),
            "response_deadline": today + timedelta(days=24),
        },
        {
            "title": "Food Desert Intervention - South Side Chicago",
            "description": "Multi-year program to establish food access points in Chicago South Side food deserts. Includes mobile markets, community gardens support, and retail partnerships.",
            "agency": "City of Chicago Department of Family and Support Services",
            "naics_code": "624210",
            "set_aside_type": "8(a)",
            "zip_code": "60621",
            "lat": 41.7795, "lng": -87.6424,
            "categories": ["mobile food pantry", "community nutrition", "retail partnerships", "fresh produce"],
            "estimated_value": 1500000, "status": "open",
            "posted_date": today - timedelta(days=1),
            "response_deadline": today + timedelta(days=40),
        },
        {
            "title": "Tribal Food Sovereignty Program - New Mexico",
            "description": "Support indigenous food sovereignty initiatives across Pueblo communities in New Mexico. Includes traditional food preservation, distribution, and cultural food programming.",
            "agency": "USDA Office of Tribal Relations",
            "naics_code": "624210",
            "set_aside_type": "Indian Economic Enterprise",
            "zip_code": "87101",
            "lat": 35.0844, "lng": -106.6504,
            "categories": ["community nutrition", "food preservation", "cultural food programs", "rural outreach"],
            "estimated_value": 420000, "status": "open",
            "posted_date": today - timedelta(days=4),
            "response_deadline": today + timedelta(days=32),
        },
        {
            "title": "Senior Meal Delivery Program - Detroit",
            "description": "Home-delivered meal program for homebound seniors in Detroit metropolitan area. 5 days/week, hot and cold meal options, dietary accommodation required.",
            "agency": "Michigan Department of Health and Human Services",
            "naics_code": "624120",
            "set_aside_type": None,
            "zip_code": "48201",
            "lat": 42.3486, "lng": -83.0567,
            "categories": ["meal preparation", "last mile delivery", "senior nutrition", "dietary accommodation"],
            "estimated_value": 680000, "status": "open",
            "posted_date": today - timedelta(days=9),
            "response_deadline": today + timedelta(days=21),
        },
        {
            "title": "Refrigerated Warehouse Expansion - Jackson MS",
            "description": "Expand refrigerated warehouse capacity for Mississippi state food distribution center. 25,000 sq ft addition with modern cold chain management.",
            "agency": "Mississippi Department of Agriculture",
            "naics_code": "493120",
            "set_aside_type": "HUBZone",
            "zip_code": "39201",
            "lat": 32.2988, "lng": -90.1848,
            "categories": ["cold storage", "warehouse distribution", "infrastructure"],
            "estimated_value": 2100000, "status": "open",
            "posted_date": today - timedelta(days=15),
            "response_deadline": today + timedelta(days=45),
        },
        {
            "title": "WIC Farmer's Market Program - Philadelphia",
            "description": "Administer WIC Farmers Market Nutrition Program across 20 market locations in Philadelphia. Includes vendor coordination, benefit processing, and nutrition education.",
            "agency": "Pennsylvania Department of Health",
            "naics_code": "624190",
            "set_aside_type": "Small Business",
            "zip_code": "19101",
            "lat": 39.9526, "lng": -75.1652,
            "categories": ["farmers market", "SNAP distribution", "community nutrition", "local sourcing"],
            "estimated_value": 190000, "status": "open",
            "posted_date": today - timedelta(days=11),
            "response_deadline": today + timedelta(days=19),
        },
        {
            "title": "Disaster Food Relief Staging - Houston",
            "description": "Establish permanent disaster food relief staging area in Houston. Hurricane season readiness with shelf-stable food stockpiles and rapid distribution capability.",
            "agency": "FEMA Region 6",
            "naics_code": "493110",
            "set_aside_type": None,
            "zip_code": "77001",
            "lat": 29.7604, "lng": -95.3698,
            "categories": ["emergency supply", "shelf-stable goods", "warehouse distribution", "disaster relief"],
            "estimated_value": 950000, "status": "open",
            "posted_date": today - timedelta(days=14),
            "response_deadline": today + timedelta(days=36),
        },
        {
            "title": "Community Kitchen Incubator - Baltimore",
            "description": "Launch shared commercial kitchen incubator for food entrepreneurs in East Baltimore. Focus on supporting BIPOC-owned food businesses in food desert areas.",
            "agency": "Baltimore Development Corporation",
            "naics_code": "722514",
            "set_aside_type": "8(a)",
            "zip_code": "21201",
            "lat": 39.2904, "lng": -76.6122,
            "categories": ["community nutrition", "food hub operations", "culinary training"],
            "estimated_value": 600000, "status": "open",
            "posted_date": today - timedelta(days=13),
            "response_deadline": today + timedelta(days=27),
        },
        {
            "title": "Produce Gleaning and Rescue - Central Valley CA",
            "description": "Coordinate produce gleaning program with Central Valley farms. Recover surplus crops for distribution to food banks and community organizations across California.",
            "agency": "California Department of Food and Agriculture",
            "naics_code": "424480",
            "set_aside_type": "Small Business",
            "zip_code": "90011",
            "lat": 33.9425, "lng": -118.2551,
            "categories": ["fresh produce", "food rescue", "local sourcing", "warehouse distribution"],
            "estimated_value": 380000, "status": "open",
            "posted_date": today - timedelta(days=6),
            "response_deadline": today + timedelta(days=26),
        },
        {
            "title": "School Breakfast Expansion - Bronx NY",
            "description": "Expand universal free breakfast program to all Bronx public schools. Requires daily delivery of breakfast items to 120+ school locations.",
            "agency": "NYC Department of Education",
            "naics_code": "722310",
            "set_aside_type": None,
            "zip_code": "10451",
            "lat": 40.8207, "lng": -73.9234,
            "categories": ["meal preparation", "institutional food service", "last mile delivery"],
            "estimated_value": 2800000, "status": "open",
            "posted_date": today - timedelta(days=2),
            "response_deadline": today + timedelta(days=38),
        },
        {
            "title": "Halal/Kosher Food Bank Supply - Dearborn MI",
            "description": "Supply culturally appropriate halal and kosher food items to food banks serving diverse communities in the Detroit-Dearborn area.",
            "agency": "Michigan Department of Agriculture",
            "naics_code": "311999",
            "set_aside_type": "Small Business",
            "zip_code": "48201",
            "lat": 42.3486, "lng": -83.0567,
            "categories": ["specialty food supply", "cultural food programs", "warehouse distribution"],
            "estimated_value": 230000, "status": "open",
            "posted_date": today - timedelta(days=7),
            "response_deadline": today + timedelta(days=23),
        },
        {
            "title": "TEFAP Distribution Network - Ohio",
            "description": "Manage The Emergency Food Assistance Program distribution across 20 Ohio counties. Includes warehouse management, transport logistics, and partner agency coordination.",
            "agency": "Ohio Department of Job and Family Services",
            "naics_code": "493110",
            "set_aside_type": None,
            "zip_code": "44101",
            "lat": 41.4993, "lng": -81.6944,
            "categories": ["warehouse distribution", "refrigerated transport", "USDA commodities", "emergency supply"],
            "estimated_value": 870000, "status": "open",
            "posted_date": today - timedelta(days=10),
            "response_deadline": today + timedelta(days=30),
        },
        {
            "title": "Summer Feeding Program - Rural Kentucky",
            "description": "Operate Summer Food Service Program at 35 sites across rural eastern Kentucky. Must prepare and deliver meals daily during June-August.",
            "agency": "Kentucky Department of Education",
            "naics_code": "722310",
            "set_aside_type": "HUBZone",
            "zip_code": "42101",
            "lat": 36.9903, "lng": -86.4436,
            "categories": ["meal preparation", "last mile delivery", "rural outreach", "institutional food service"],
            "estimated_value": 410000, "status": "open",
            "posted_date": today - timedelta(days=4),
            "response_deadline": today + timedelta(days=20),
        },
        {
            "title": "Urban Agriculture Support - Cleveland",
            "description": "Provide technical assistance and supply chain support for urban farms in Cleveland. Connect urban growers to institutional buyers and food banks.",
            "agency": "USDA Agricultural Marketing Service",
            "naics_code": "115112",
            "set_aside_type": "Small Business",
            "zip_code": "44101",
            "lat": 41.4993, "lng": -81.6944,
            "categories": ["local sourcing", "food hub operations", "community nutrition", "fresh produce"],
            "estimated_value": 275000, "status": "open",
            "posted_date": today - timedelta(days=8),
            "response_deadline": today + timedelta(days=32),
        },
        {
            "title": "Border Community Food Access - El Paso",
            "description": "Improve food access in El Paso colonias and underserved border communities. Mobile markets, community food distribution, and SNAP enrollment assistance.",
            "agency": "Texas Health and Human Services Commission",
            "naics_code": "624210",
            "set_aside_type": None,
            "zip_code": "79901",
            "lat": 31.7619, "lng": -106.4850,
            "categories": ["mobile food pantry", "SNAP distribution", "community nutrition", "rural outreach"],
            "estimated_value": 340000, "status": "open",
            "posted_date": today - timedelta(days=5),
            "response_deadline": today + timedelta(days=25),
        },
        {
            "title": "Food Recovery & Composting - Miami-Dade",
            "description": "Establish food recovery program with restaurants and grocers in Miami-Dade County. Rescue edible food for distribution; compost remainder.",
            "agency": "Miami-Dade County Solid Waste Management",
            "naics_code": "562219",
            "set_aside_type": "Small Business",
            "zip_code": "33101",
            "lat": 25.7617, "lng": -80.1918,
            "categories": ["food rescue", "warehouse distribution", "community nutrition"],
            "estimated_value": 520000, "status": "open",
            "posted_date": today - timedelta(days=3),
            "response_deadline": today + timedelta(days=28),
        },
        {
            "title": "Native American Food Distribution - Oklahoma",
            "description": "USDA Food Distribution Program on Indian Reservations (FDPIR) for Oklahoma tribal nations. Monthly food package assembly and distribution to 8,000+ households.",
            "agency": "USDA Food and Nutrition Service",
            "naics_code": "624210",
            "set_aside_type": "Indian Economic Enterprise",
            "zip_code": "73101",
            "lat": 35.4676, "lng": -97.5164,
            "categories": ["USDA commodities", "warehouse distribution", "cultural food programs", "rural outreach"],
            "estimated_value": 710000, "status": "open",
            "posted_date": today - timedelta(days=11),
            "response_deadline": today + timedelta(days=34),
        },
        {
            "title": "Medically Tailored Meals - Richmond VA",
            "description": "Provide medically tailored meals to individuals with chronic conditions through Medicaid waiver program. Requires registered dietitian oversight and home delivery.",
            "agency": "Virginia Department of Medical Assistance Services",
            "naics_code": "624120",
            "set_aside_type": None,
            "zip_code": "23219",
            "lat": 37.5407, "lng": -77.4360,
            "categories": ["meal preparation", "dietary accommodation", "last mile delivery", "senior nutrition"],
            "estimated_value": 580000, "status": "open",
            "posted_date": today - timedelta(days=9),
            "response_deadline": today + timedelta(days=31),
        },
        {
            "title": "Regional Food Bank Cold Storage - St. Louis",
            "description": "Install and manage industrial cold storage system for St. Louis Area Foodbank. 40,000 sq ft facility handling 30M+ pounds of food annually.",
            "agency": "Missouri Department of Social Services",
            "naics_code": "493120",
            "set_aside_type": "Small Business",
            "zip_code": "63101",
            "lat": 38.6270, "lng": -90.1994,
            "categories": ["cold storage", "warehouse distribution", "infrastructure"],
            "estimated_value": 1800000, "status": "open",
            "posted_date": today - timedelta(days=16),
            "response_deadline": today + timedelta(days=44),
        },
        {
            "title": "Nutrition Education & Cooking Classes - DC",
            "description": "Deliver nutrition education and cooking skills program across 25 community sites in Washington DC Wards 7 and 8. Target: 2,000 residents annually.",
            "agency": "DC Department of Health",
            "naics_code": "611699",
            "set_aside_type": "8(a)",
            "zip_code": "20001",
            "lat": 38.9072, "lng": -77.0369,
            "categories": ["community nutrition", "culinary training", "rural outreach"],
            "estimated_value": 165000, "status": "open",
            "posted_date": today - timedelta(days=6),
            "response_deadline": today + timedelta(days=22),
        },
        {
            "title": "Grocery Delivery for Homebound - Milwaukee",
            "description": "Grocery delivery service for homebound individuals in Milwaukee County. Partnership with local grocery stores, weekly deliveries to 1,500+ households.",
            "agency": "Milwaukee County Department on Aging",
            "naics_code": "492210",
            "set_aside_type": None,
            "zip_code": "53201",
            "lat": 43.0389, "lng": -87.9065,
            "categories": ["last mile delivery", "senior nutrition", "retail partnerships"],
            "estimated_value": 290000, "status": "open",
            "posted_date": today - timedelta(days=7),
            "response_deadline": today + timedelta(days=21),
        },
        {
            "title": "Midwest Produce Hub - Indianapolis",
            "description": "Establish regional produce aggregation hub in Indianapolis connecting Indiana, Ohio, and Kentucky farms to institutional buyers and food assistance programs.",
            "agency": "Indiana State Department of Agriculture",
            "naics_code": "424480",
            "set_aside_type": "Small Business",
            "zip_code": "46201",
            "lat": 39.7684, "lng": -86.1581,
            "categories": ["food hub operations", "local sourcing", "fresh produce", "warehouse distribution"],
            "estimated_value": 1100000, "status": "open",
            "posted_date": today - timedelta(days=13),
            "response_deadline": today + timedelta(days=37),
        },
        {
            "title": "Emergency SNAP Replacement - Jacksonville FL",
            "description": "Provide emergency SNAP benefit replacement and food distribution following natural disasters in the Jacksonville metropolitan area.",
            "agency": "Florida Department of Children and Families",
            "naics_code": "624210",
            "set_aside_type": None,
            "zip_code": "32099",
            "lat": 30.3322, "lng": -81.6557,
            "categories": ["SNAP distribution", "emergency supply", "last mile delivery", "disaster relief"],
            "estimated_value": 430000, "status": "open",
            "posted_date": today - timedelta(days=2),
            "response_deadline": today + timedelta(days=26),
        },
    ]
    for s in sols:
        db.session.add(Solicitation(**s))


def seed_organizations():
    orgs = [
        {
            "name": "Delta Fresh Foods Co-op",
            "org_type": "supplier",
            "description": "Farmer-owned cooperative specializing in fresh produce distribution across the Mississippi Delta. Strong relationships with local growers and community organizations.",
            "zip_code": "38701",
            "lat": 33.4015, "lng": -91.0618,
            "contact_email": "contact@deltafreshfoods.coop",
            "capabilities": ["fresh produce", "local sourcing", "cold storage", "last mile delivery"],
            "certifications": ["USDA", "SBA 8(a)", "HUBZone"],
            "service_radius_miles": 200,
        },
        {
            "name": "Southern Cold Chain Logistics",
            "org_type": "distributor",
            "description": "Full-service cold chain logistics provider serving the Southeast US. Fleet of 50+ refrigerated trucks with GPS tracking and temperature monitoring.",
            "zip_code": "30303",
            "lat": 33.7490, "lng": -84.3880,
            "contact_email": "ops@southerncoldchain.com",
            "capabilities": ["cold storage", "refrigerated transport", "warehouse distribution", "last mile delivery"],
            "certifications": ["USDA", "FDA"],
            "service_radius_miles": 500,
        },
        {
            "name": "Mid-South Food Bank Alliance",
            "org_type": "nonprofit",
            "description": "Network of food banks serving Tennessee, Mississippi, and Arkansas. Operates 12 distribution centers and serves 500,000 individuals monthly.",
            "zip_code": "38103",
            "lat": 35.1495, "lng": -90.0490,
            "contact_email": "info@midsouthfoodbank.org",
            "capabilities": ["warehouse distribution", "last mile delivery", "community nutrition", "USDA commodities", "mobile food pantry"],
            "certifications": ["Feeding America", "USDA"],
            "service_radius_miles": 300,
        },
        {
            "name": "Bayou Provisions LLC",
            "org_type": "supplier",
            "description": "Louisiana-based food supplier specializing in shelf-stable goods and emergency food supplies. Experienced in hurricane preparedness food staging.",
            "zip_code": "70112",
            "lat": 29.9511, "lng": -90.0715,
            "contact_email": "sales@bayouprovisions.com",
            "capabilities": ["shelf-stable goods", "emergency supply", "warehouse distribution", "disaster relief"],
            "certifications": ["SBA 8(a)", "FEMA vendor"],
            "service_radius_miles": 350,
        },
        {
            "name": "Heartland Meal Services",
            "org_type": "supplier",
            "description": "Institutional meal preparation company serving schools, senior centers, and correctional facilities across the Midwest.",
            "zip_code": "46201",
            "lat": 39.7684, "lng": -86.1581,
            "contact_email": "contracts@heartlandmeals.com",
            "capabilities": ["meal preparation", "institutional food service", "dietary accommodation", "last mile delivery"],
            "certifications": ["USDA", "ServSafe"],
            "service_radius_miles": 400,
        },
        {
            "name": "Community Harvest Network",
            "org_type": "nonprofit",
            "description": "Food rescue organization recovering surplus food from farms, restaurants, and grocers. Redistributes 10M+ pounds of food annually across the Southeast.",
            "zip_code": "37203",
            "lat": 36.1627, "lng": -86.7816,
            "contact_email": "hello@communityharvestnetwork.org",
            "capabilities": ["food rescue", "fresh produce", "community nutrition", "local sourcing", "warehouse distribution"],
            "certifications": ["Feeding America", "USDA"],
            "service_radius_miles": 250,
        },
        {
            "name": "Great Lakes Cold Storage Inc",
            "org_type": "distributor",
            "description": "Industrial cold storage and distribution facility in Detroit. 100,000 sq ft facility with blast freezing capability.",
            "zip_code": "48201",
            "lat": 42.3486, "lng": -83.0567,
            "contact_email": "info@greatlakescold.com",
            "capabilities": ["cold storage", "warehouse distribution", "refrigerated transport", "infrastructure"],
            "certifications": ["USDA", "SQF Certified"],
            "service_radius_miles": 300,
        },
        {
            "name": "Nourish Chicago",
            "org_type": "nonprofit",
            "description": "Chicago-based nonprofit operating mobile food pantries and community kitchens on the South and West sides. Serves 50,000 households monthly.",
            "zip_code": "60621",
            "lat": 41.7795, "lng": -87.6424,
            "contact_email": "partners@nourishchicago.org",
            "capabilities": ["mobile food pantry", "community nutrition", "meal preparation", "culinary training", "fresh produce"],
            "certifications": ["Feeding America", "SBA 8(a)"],
            "service_radius_miles": 100,
        },
        {
            "name": "Pueblo Food Sovereignty Project",
            "org_type": "nonprofit",
            "description": "Indigenous-led organization supporting food sovereignty across New Mexico Pueblo communities. Operates traditional food preservation and distribution programs.",
            "zip_code": "87101",
            "lat": 35.0844, "lng": -106.6504,
            "contact_email": "info@pueblofoodsovereignty.org",
            "capabilities": ["cultural food programs", "food preservation", "community nutrition", "rural outreach"],
            "certifications": ["Indian Economic Enterprise", "USDA"],
            "service_radius_miles": 200,
        },
        {
            "name": "TechBridge Solutions",
            "org_type": "supplier",
            "description": "Technology company specializing in government food assistance program platforms. Built SNAP/WIC integration systems for 5 states.",
            "zip_code": "36104",
            "lat": 32.3668, "lng": -86.2999,
            "contact_email": "gov@techbridgesolutions.com",
            "capabilities": ["technology platform", "SNAP distribution", "rural outreach"],
            "certifications": ["HUBZone", "FedRAMP"],
            "service_radius_miles": 1000,
        },
        {
            "name": "East Coast Fresh Distributors",
            "org_type": "distributor",
            "description": "Full-service produce distributor serving the Eastern seaboard. Direct relationships with 200+ farms from Florida to Maine.",
            "zip_code": "19101",
            "lat": 39.9526, "lng": -75.1652,
            "contact_email": "sales@eastcoastfresh.com",
            "capabilities": ["fresh produce", "refrigerated transport", "local sourcing", "last mile delivery", "institutional food service"],
            "certifications": ["USDA", "GAP Certified"],
            "service_radius_miles": 600,
        },
        {
            "name": "Gulf Coast Emergency Services",
            "org_type": "distributor",
            "description": "Emergency logistics provider specializing in disaster food relief along the Gulf Coast. Mobilizes within 24 hours for hurricane and flood response.",
            "zip_code": "77001",
            "lat": 29.7604, "lng": -95.3698,
            "contact_email": "dispatch@gulfcoastemergency.com",
            "capabilities": ["emergency supply", "disaster relief", "shelf-stable goods", "last mile delivery", "warehouse distribution"],
            "certifications": ["FEMA vendor", "USDA"],
            "service_radius_miles": 500,
        },
        {
            "name": "Baltimore Community Kitchen Collective",
            "org_type": "nonprofit",
            "description": "Shared commercial kitchen and food entrepreneur incubator in East Baltimore. Supports 40+ BIPOC-owned food businesses with training and commercial kitchen access.",
            "zip_code": "21201",
            "lat": 39.2904, "lng": -76.6122,
            "contact_email": "info@bmorekitchen.org",
            "capabilities": ["culinary training", "community nutrition", "food hub operations", "meal preparation"],
            "certifications": ["SBA 8(a)", "Maryland MBE"],
            "service_radius_miles": 75,
        },
        {
            "name": "Buckeye Harvest Hub",
            "org_type": "distributor",
            "description": "Ohio food hub connecting small farms to institutional buyers, food banks, and retail. Operates aggregation and distribution center in Cleveland.",
            "zip_code": "44101",
            "lat": 41.4993, "lng": -81.6944,
            "contact_email": "orders@buckeyeharvesthub.com",
            "capabilities": ["food hub operations", "local sourcing", "fresh produce", "warehouse distribution", "refrigerated transport"],
            "certifications": ["USDA", "GAP Certified", "Small Business"],
            "service_radius_miles": 250,
        },
        {
            "name": "Lone Star Food Systems",
            "org_type": "supplier",
            "description": "Texas-based food systems company operating cold storage facilities and distribution networks. Serves military bases, schools, and government programs.",
            "zip_code": "75201",
            "lat": 32.7872, "lng": -96.7985,
            "contact_email": "government@lonestarfood.com",
            "capabilities": ["cold storage", "warehouse distribution", "institutional food service", "shelf-stable goods", "refrigerated transport"],
            "certifications": ["USDA", "DoD vendor", "HUBZone"],
            "service_radius_miles": 500,
        },
        {
            "name": "Carolina Nutrition Partners",
            "org_type": "nonprofit",
            "description": "NC/SC nutrition nonprofit providing community nutrition education, cooking classes, and farmers market SNAP matching programs.",
            "zip_code": "28201",
            "lat": 35.2271, "lng": -80.8431,
            "contact_email": "programs@carolinanutrition.org",
            "capabilities": ["community nutrition", "culinary training", "farmers market", "SNAP distribution"],
            "certifications": ["Feeding America"],
            "service_radius_miles": 200,
        },
        {
            "name": "Midwest Senior Nutrition Inc",
            "org_type": "supplier",
            "description": "Specialized provider of senior nutrition services including Meals on Wheels, congregate meals, and medically tailored meal programs.",
            "zip_code": "53201",
            "lat": 43.0389, "lng": -87.9065,
            "contact_email": "info@midwestseniornutrition.com",
            "capabilities": ["meal preparation", "senior nutrition", "dietary accommodation", "last mile delivery"],
            "certifications": ["USDA", "ServSafe"],
            "service_radius_miles": 300,
        },
        {
            "name": "Sooner State Food Co-op",
            "org_type": "supplier",
            "description": "Oklahoma cooperative of Native American food producers. Specializes in traditional foods and USDA commodity distribution for tribal communities.",
            "zip_code": "73101",
            "lat": 35.4676, "lng": -97.5164,
            "contact_email": "coop@soonerfood.org",
            "capabilities": ["USDA commodities", "cultural food programs", "warehouse distribution", "rural outreach"],
            "certifications": ["Indian Economic Enterprise", "USDA", "SBA 8(a)"],
            "service_radius_miles": 300,
        },
        {
            "name": "Sunshine State Logistics",
            "org_type": "distributor",
            "description": "Florida food logistics company with temperature-controlled fleet serving the entire state. Specializes in last-mile delivery to food banks and social service agencies.",
            "zip_code": "32099",
            "lat": 30.3322, "lng": -81.6557,
            "contact_email": "logistics@sunshinestatelog.com",
            "capabilities": ["refrigerated transport", "last mile delivery", "warehouse distribution", "emergency supply", "SNAP distribution"],
            "certifications": ["USDA", "Small Business"],
            "service_radius_miles": 400,
        },
        {
            "name": "Appalachian Food Network",
            "org_type": "nonprofit",
            "description": "Regional nonprofit fighting food insecurity in Appalachian communities across KY, TN, and VA. Operates mobile markets and summer feeding programs.",
            "zip_code": "42101",
            "lat": 36.9903, "lng": -86.4436,
            "contact_email": "connect@appfoodnetwork.org",
            "capabilities": ["mobile food pantry", "rural outreach", "meal preparation", "institutional food service", "community nutrition"],
            "certifications": ["Feeding America", "HUBZone", "USDA"],
            "service_radius_miles": 250,
        },
    ]
    for o in orgs:
        db.session.add(Organization(**o))


if __name__ == "__main__":
    seed()
